from datetime import datetime, timezone

import boto3
from django.conf import settings
from django.core.management.base import BaseCommand
from rest_framework.request import Request
from rest_framework.test import APIRequestFactory
from rest_framework_xml.renderers import XMLRenderer

from api.serializers import ErpSerializer
from erp.models import Erp

ACTIVITIES = [
    "Accrobranche",
    "Achat or",
    "Achat, vente, réparation de matériel informatique et téléphonique",
    "Activités nautiques",
    "Acupuncture",
    "Administration publique",
    "Aéroport, aérodrome",
    "Agence départementale d'information sur le logement",
    "Agence de publicité",
    "Agence de travail temporaire",
    "Agence de voyage",
    "Agence événementielle",
    "Agence immobilière",
    "Agence matrimoniale",
    "Aide sociale à l'enfance",
    "Aire d'accueil de gens du voyage",
    "Ambulances",
    "Aménagement intérieur de la maison",
    "Anesthésie",
    "Animalerie",
    "Antiquaire",
    "Apiculteur",
    "Aquarium",
    "Architecte",
    "Archives",
    "Arène",
    "Armurerie coutellerie",
    "Art, centre d'art",
    "Articles de fête, carnaval ou divertissement",
    "Artisanat",
    "Arts de la table, vaisselle",
    "Association",
    "Association aide aux victimes",
    "Assurance",
    "Astrologie, voyance, spiritisme",
    "Athlétisme",
    "Auberge de jeunesse, centre international de séjour",
    "Auditorium et salle de conférence",
    "Auto école",
    "Autres activités des médecins spécialistes",
    "Autres établissements pour adultes et familles en difficulté",
    "Avocat",
    "Bailleur social",
    "Banques, caisses d'épargne",
    "Barbier",
    "Bar tabac",
    "Bâtiment d'accueil",
    "Bazar",
    "Bibliothèque médiathèque",
    "Bien-être",
    "Bijouterie fantaisie",
    "Bijouterie joaillerie",
    "Biscuiterie",
    "Blanchisserie teinturerie",
    "Boucherie / commerce de viande",
    "Boulangerie Pâtisserie",
    "Boulodrome",
    "Boutique de mariage",
    "Bowling",
    "Bricolage, matériaux, travaux",
    "Brocante",
    "Bureau de change",
    "Bureau de douane",
    "Bureau de poste",
    "Bureau de vote",
    "Café, bar, brasserie",
    "Caisse d'allocations familiales (caf)",
    "Camping caravaning",
    "Cantine",
    "Cardiologie",
    "Carrosserie",
    "Casino",
    "Caviste / commerce de détail de boissons",
    "Centrale nucléaire",
    "Centre commercial",
    "Centre culturel",
    "Centre de gestion de la fonction publique territoriale",
    "Centre de loisirs",
    "Centre de protection maternelle et infantile (pmi)",
    "Centre de ressources et d'information",
    "Centre de vacances",
    "Centre de vaccination",
    "Centre d'examen",
    "Centre d’information et d’orientation",
    "Centre d'information sur les droits des femmes et des familles",
    "Centre équestre",
    "Centre médical",
    "Centre national de la fonction publique territoriale",
    "Centre religieux",
    "Centre social",
    "Chambre agriculture",
    "Chambre de commerce et d'industrie",
    "Chambre d'hôtes, gîte, pension, meublé de tourisme",
    "Chambre metier",
    "Chapeaux et couvre-chefs",
    "Charcuterie",
    "Château",
    "Chaussures",
    "Chenil, fourrière",
    "Chirurgie",
    "Chocolatier",
    "Cigarette électronique",
    "Cimetière",
    "Cinéma",
    "Circuit sportif deux roues / voiture",
    "Clinique",
    "Club de sport",
    "Coaching",
    "Coiffure",
    "Collectivité territoriale",
    "Collège",
    "Commerce",
    "Commerce automobile",
    "Commerce bio",
    "Commissariat de Police",
    "Commission conciliation",
    "Complexe sportif",
    "Comptable expert-comptable",
    "Concessionnaire automobile",
    "Confiserie",
    "Conservatoire et école de musique",
    "Construction, rénovation",
    "Contrôle technique auto",
    "Coopérative agricole",
    "Cordonnerie serrurerie",
    "Courtier",
    "Couture, retouche",
    "Coworking",
    "Crèche",
    "Cycle vente et entretien",
    "Cyclisme",
    "Déchetterie",
    "Décoration Design",
    "Déménageur",
    "Dentiste, chirurgien dentiste",
    "Dermatologie vénéréologie",
    "Désinfection, lutte contre les nuisibles",
    "Diététicien, nutritionniste",
    "Direction départementale de la protection des populations",
    "Direction départementale de l'emploi, du travail, des solidarités et de la protection des populations",
    "Discothèque",
    "Disquaire",
    "Distribution spécialisée / commerce de gros",
    "Dressage, éducation canine",
    "Droguerie",
    "Ecole de danse",
    "Ecole de ski et snowboard",
    "École élémentaire",
    "École maternelle",
    "École primaire (regroupement maternelle et élémentaire)",
    "Ehpad",
    "Électricien",
    "Électroménager et matériel audio-vidéo",
    "Emploi, formation",
    "Encadreur enlumineur",
    "Endocrinologue",
    "Enseignement culturel",
    "Entretien de piscine",
    "Épicerie",
    "Epicerie fine",
    "Équipements du foyer",
    "Equipement sportif",
    "Ergothérapeute",
    "Espace collaboratif",
    "Espace numérique",
    "Espace vert et naturel",
    "Etablissement de prévention",
    "Établissement de santé",
    "Établissement militaire",
    "Etablissement pénitentiaire",
    "Établissement thermal",
    "Evénement culturel",
    "Fédération départementale pour la pêche et la protection du milieu aquatique",
    "Ferme",
    "Fleuriste",
    "Friperie",
    "Fromagerie",
    "Fruits et légumes",
    "Galerie d'art",
    "Garage automobile",
    "Garde meuble",
    "Garderie",
    "Gare routière",
    "Gare sncf",
    "Gare tgv",
    "Gastro-entérologie hépatologie",
    "Gendarmerie",
    "Géomètre",
    "Glacier",
    "Greffe des associations",
    "Groupe scolaire",
    "Guichet france services",
    "Gymnase",
    "Gynécologie",
    "Hébergement insolite",
    "Hématologie",
    "Hôpital",
    "Horlogerie",
    "Hôtel",
    "Hôtel restaurant",
    "Huissier",
    "Hypermarché",
    "Hypnothérapeute",
    "Immobilier",
    "Imprimerie photocopie reliure",
    "Infirmier",
    "Information Touristique",
    "Informatique",
    "Institut de formation, de recherche",
    "Instruments et matériel de musique",
    "Jardin botanique et/ou zoologique",
    "Jardinerie",
    "Jeux jouets",
    "Jeux vidéo",
    "Karaoké",
    "Kinésiologue",
    "Kinésithérapeute",
    "Kiosque (théâtre, pizza, journaux)",
    "Laboratoire d'analyse médicale",
    "Laverie",
    "Librairie",
    "Lieu de culte",
    "Lieu de visite",
    "Lingerie sous-vêtements",
    "Literie",
    "Location articles loisirs et sport",
    "Location de matériels",
    "Location saisonnière",
    "Location véhicules",
    "Loisirs créatifs",
    "Luminaire",
    "Lycée",
    "Magasin d'appareils auditifs",
    "Magasin de bois de chauffage",
    "Magasin de cbd",
    "Magasin de déguisements",
    "Magasin de souvenirs",
    "Magasin de tissus",
    "Mairie",
    "Maison départementale des personnes handicapées",
    "Maison de santé ou centre de santé",
    "Maison de services au public",
    "Marché",
    "Maroquinerie sellerie articles de voyage",
    "Massages",
    "Matériel de pêche",
    "Médecine du travail",
    "Médecin généraliste",
    "Médecin orl",
    "Médiation",
    "Menuiserie, ébénisterie",
    "Mercerie",
    "Métallerie, chaudronnerie",
    "Meubles ameublement",
    "Mission d'accueil et d'information des associations",
    "Mission locale pour l'insertion professionnelle et sociale des jeunes",
    "Monument historique",
    "Motocycle vente et entretien",
    "Musée",
    "Musique",
    "Naturopathie, herboristerie",
    "Néphrologue",
    "Neurologie",
    "Notaire",
    "Numérique",
    "Observatoire, astronomie",
    "Oenotourisme",
    "Office de tourisme",
    "Opéra",
    "Ophtalmologie",
    "Opticien",
    "Ordre des avocats",
    "Organisation patronale, professionnelle, syndicale",
    "Organisme de conseil",
    "Orthodontie",
    "Orthopédie",
    "Orthophonie",
    "Orthoptie",
    "Ostéopathie",
    "Oto-rhino-laryngologie",
    "Papeterie, presse, journaux",
    "Parc",
    "Parc d’attraction",
    "Parc des expositions",
    "Parfumerie, cosmétique",
    "Parking & stationnement",
    "Patinoire",
    "Pédiatrie",
    "Pédicure-podologue",
    "Pépinière",
    "Personnes âgées : foyer restaurant",
    "Personnes âgées : hébergement",
    "Pharmacie",
    "Photographie",
    "Piscine, centre aquatique",
    "Plage, zone de baignade",
    "Plateaux et terrains de jeux extérieurs",
    "Plomberie, chauffage",
    "Pneumologie",
    "Point accueil numerique",
    "Point conseil budget",
    "Point d'information local dédié aux personnes âgées",
    "Point information jeunesse",
    "Point justice",
    "Poissonnerie / commerce de poissons, crustacés et mollusques",
    "Pompes funèbres",
    "Port",
    "Poterie verrerie céramique",
    "Pressing, nettoyage",
    "Primeur",
    "Produits de terroir",
    "Produits d'occasion",
    "Produits surgelés",
    "Profession libérale",
    "Psychologie, Psychiatrie",
    "Psychomotricien",
    "Puériculture",
    "Radiodiagnostic et imagerie médicale",
    "Randonnées pédestres ou vélos",
    "Refuge animalier",
    "Rempailleur tapissier chaises fauteuils",
    "Réparation auto et de matériel agricole",
    "Résidence de tourisme",
    "Résidence, foyer",
    "Ressourcerie",
    "Restaurant",
    "Restaurant scolaire",
    "Restauration rapide",
    "Revêtements murs et sols",
    "Rhumatologie",
    "Sage-femme",
    "Salle de combat",
    "Salle de concert",
    "Salle de danse",
    "Salle de jeux",
    "Salle de remise en forme",
    "Salle de réunion ou réception",
    "Salle des fêtes",
    "Salle de spectacle",
    "Salle multisports",
    "Salle non spécialisée",
    "Salle spécialisée",
    "Salon de thé",
    "Sécurité sociale, mutuelle santé",
    "Service médico-social",
    "Service ou aide à domicile",
    "Services techniques",
    "Sex shop",
    "Skatepark",
    "Soin, médecine douce",
    "Soins de beauté, esthétique",
    "Sophrologue",
    "Spa",
    "Sports et loisirs",
    "Stade",
    "Station lavage auto",
    "Station service",
    "Stockage",
    "Stomatologie",
    "Supérette",
    "Supermarché",
    "Syndic, gérance immo",
    "Tabac",
    "Tatouage Piercing",
    "Taxi",
    "Taxidermie",
    "Téléphonie",
    "Tennis",
    "Textile hors habillement",
    "Thalassothérapie",
    "Théâtre",
    "Tiers lieu",
    "Toilettes publiques",
    "Toiletteur",
    "Traduction et interprétation",
    "Traiteur, gastronomie",
    "Transport",
    "Trésorerie",
    "Tribunal",
    "Université ou école supérieure",
    "Urologie",
    "Vente à distance",
    "Vente d'articles de sport",
    "Vente de cafés et thés",
    "Vente de matériel et équipement industriels",
    "Vente de matériel médical",
    "Vente de matériel pour piscine",
    "Vêtements",
    "Vétérinaire",
    "Village de vacances",
    "Viticulteur",
]


class Command(BaseCommand):
    help = "Export ERP in XML format to S3"

    def handle(self, *args, **options):
        now = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")

        self.stdout.write("Serialize data...")
        qs = Erp.objects.published().select_related("user", "accessibilite", "activite")
        qs = qs.filter(activite__nom__in=ACTIVITIES)

        server_name = settings.SITE_HOST
        factory = APIRequestFactory(SERVER_NAME=server_name)
        fake_request = factory.get("/")
        fake_request = Request(fake_request)

        data = {
            "erps": ErpSerializer(qs, many=True, context={"request": fake_request}).data,
        }

        renderer = XMLRenderer()
        xml_bytes = renderer.render(
            data,
            accepted_media_type="application/xml",
            renderer_context={},
        )

        bucket_name = settings.S3_EXPORT_BUCKET_NAME
        file_name = f"export_{now}_full.xml"

        self.stdout.write(f"Upload to S3 : {bucket_name}/{file_name}")

        s3 = boto3.client(
            "s3",
            endpoint_url=settings.S3_EXPORT_BUCKET_ENDPOINT_URL,
            # NOTE: required with boto3 1.36.x
            # config=Config(request_checksum_calculation="when_required", response_checksum_validation="when_required"),
        )

        s3.put_object(
            Bucket=bucket_name,
            Key=file_name,
            Body=xml_bytes,
            ContentType="application/xml",
        )

        file_url = s3.generate_presigned_url(
            "get_object",
            Params={"Bucket": bucket_name, "Key": file_name},
            ExpiresIn=604800,
        )

        self.stdout.write(self.style.SUCCESS(f"Export terminated, link available during 7 days: {file_url}"))
