# See https://pre-commit.com for more information
default_language_version:
  # default language version for each language used in the repository
  python: python3.9
repos:
-   repo: https://github.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        entry: bash -c "flake8"
