import os
from unittest.mock import MagicMock

import pytest
from django.contrib.gis.geos import Point
from django.db import connection
from pytest_factoryboy import register

from erp.models import Activite, ActivitiesGroup
from erp.provider import geocoder
from tests.factories import AccessibiliteFactory, ErpFactory, UserFactory


@pytest.fixture(scope="session")
def django_db_setup(django_db_setup, django_db_blocker):
    assert os.environ.get("DJANGO_SETTINGS_MODULE") == "core.settings_test"

    # Installe les extensions postgres pour la suite de test pytest
    with django_db_blocker.unblock(), connection.cursor() as cursor:
        cursor.execute("CREATE EXTENSION IF NOT EXISTS postgis")
        cursor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
        cursor.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
        cursor.execute("DROP TEXT SEARCH CONFIGURATION IF EXISTS french_unaccent cascade")
        cursor.execute("CREATE TEXT SEARCH CONFIGURATION french_unaccent( COPY = french )")
        cursor.execute(
            "ALTER TEXT SEARCH CONFIGURATION french_unaccent ALTER MAPPING FOR hword, hword_part, word WITH unaccent, french_stem"
        )


@pytest.fixture(autouse=True)
def mock_geocode(request, mocker):
    """
    NOTE: use @pytest.mark.disable_geocode_autouse to skip this autoused fixture
    """

    def _result(*args, **kwargs):
        # naive address splitting, could be enhanced
        numero_voie, commune = args[0].split(", ")
        numero_voie = numero_voie.split(" ")
        numero = numero_voie[0]
        voie = " ".join(numero_voie[1:])

        return {
            "geom": Point((3, 43), srid=4326),
            "numero": numero,
            "voie": voie.capitalize(),
            "lieu_dit": None,
            "code_postal": kwargs.get("postcode") or "34830",
            "commune": commune,
            "code_insee": kwargs.get("postcode") or "34830",
            "ban_id": "abcd_12345",
            "provider": "ban",
        }

    if "disable_geocode_autouse" in request.keywords:
        yield
    else:
        yield mocker.patch.object(geocoder, "geocode", side_effect=_result)


@pytest.fixture(autouse=True)
def mock_brevo(mocker):
    mocker.patch("sib_api_v3_sdk.ContactsApi.get_contact_info", return_value=MagicMock(id=1))
    mocker.patch("sib_api_v3_sdk.ContactsApi.update_contact", return_value=True)
    mocker.patch("sib_api_v3_sdk.ContactsApi.add_contact_to_list", return_value=True)
    mocker.patch("sib_api_v3_sdk.TransactionalEmailsApi.send_transac_email", return_value=True)


@pytest.fixture
def activite(db):
    list_activite = [
        "Accessoires",
        "Accompagnement personnes agees",
        "Accrobranche",
        "Achat or",
        "Achat, vente, réparation de matériel informatique et téléphonique",
        "Acupuncture",
        "Administration publique",
        "Aéroport, aérodrome",
        "Agence départementale d'information sur le logement",
        "Agence de publicité",
        "Agence de travail temporaire",
        "Agence de voyage",
        "Agence événementielle",
        "Agence immobilière",
        "Agence matrimoniale",
        "Aide sociale à l'enfance : action éducative",
        "Ambulances",
        "Aménagement maison : cuisine salle de bain salon",
        "Anesthésie",
        "Animalerie",
        "Antiquaire",
        "Apiculteur",
        "Aquarium",
        "Architecte",
        "Arène",
        "Armurerie coutellerie",
        "Art",
        "Artisanat",
        "Arts de la table",
        "Association",
        "Association aide aux victimes",
        "Assurance",
        "Athlétisme",
        "Auberge de jeunesse, centre international de séjour",
        "Audio prothésiste",
        "Auditorium et salle de conférence",
        "Auto école",
        "Autre",
        "Autres établissements pour adultes et familles en difficulté",
        "Avocat",
        "Bailleur social",
        "Banques, caisses d'épargne",
        "Barbier",
        "Bar tabac",
        "Bâtiment d'accueil",
        "Bazar",
        "Bibliothèque médiathèque",
        "Bien-être",
        "Bijouterie fantaisie",
        "Bijouterie joaillerie",
        "Biscuiterie",
        "Blanchisserie teinturerie",
        "Boucherie / commerce de viande",
        "Boulangerie Pâtisserie",
        "Boulodrome",
        "Boutique de mariage",
        "Bowling",
        "Bricolage, matériaux, travaux",
        "Brocante",
        "Bureau de change",
        "Bureau de douane",
        "Bureau de poste",
        "Café, bar, brasserie",
        "Caisse d'allocations familiales (caf)",
        "Camping caravaning",
        "Cantine",
        "Cardiologie",
        "Carrosserie",
        "Casino",
        "Caviste / commerce de détail de boissons",
        "Centrale nucléaire",
        "Centre commercial",
        "Centre culturel",
        "Centre de gestion de la fonction publique territoriale",
        "Centre de loisirs",
        "Centre de protection maternelle et infantile (pmi)",
        "Centre de ressources et d'information",
        "Centre de vacances",
        "Centre de vaccination",
        "Centre d'examen",
        "Centre d’information et d’orientation",
        "Centre d'information sur les droits des femmes et des familles",
        "Centre équestre",
        "Centre médical",
        "Centre national de la fonction publique territoriale",
        "Centre religieux",
        "Centre social",
        "Chambre agriculture",
        "Chambre de commerce et d'industrie",
        "Chambre d'hôtes, gîte, pension, meublé de tourisme",
        "Chambre metier",
        "Chapeaux et couvre-chefs",
        "Charcuterie",
        "Château",
        "Chaussures",
        "Chenil, fourrière",
        "Chirurgie",
        "Chirurgien dentiste",
        "Chocolatier",
        "Cigarette électronique",
        "Cimetière",
        "Cinéma",
        "Circuit sportif deux roues / voiture",
        "Clinique",
        "Club de sport",
        "Coaching",
        "Coiffure",
        "Collectivité territoriale",
        "Collège",
        "Commerce",
        "Commerce automobile",
        "Commerce bio",
        "Commissariat de Police",
        "Commission conciliation",
        "Comptable expert-comptable",
        "Concessionnaire automobile",
        "Confiserie",
        "Conservatoire et école de musique",
        "Construction, rénovation",
        "Contrôle technique auto",
        "Coopérative agricole",
        "Cordonnerie serrurerie",
        "Courtier",
        "Coworking",
        "Crèche",
        "Crèmerie Fromagerie",
        "Cycle vente et entretien",
        "Cyclisme",
        "Déchetterie",
        "Décoration Design",
        "Déménageur",
        "Dermatologie vénéréologie",
        "Direction départementale de la protection des populations",
        "Direction départementale de l'emploi, du travail, des solidarités et de la protection des populations",
        "Discothèque",
        "Disquaire",
        "Distribution spécialisée / commerce de gros",
        "Droguerie",
        "Ecole de danse",
        "Ecole de ski et snowboard",
        "École élémentaire",
        "École maternelle",
        "École primaire (regroupement maternelle et élémentaire)",
        "Ehpad",
        "Électricien",
        "Électroménager et matériel audio-vidéo",
        "Emploi, formation",
        "Encadreur enlumineur",
        "Endocrinologue",
        "Enseignement culturel",
        "Entretien de piscine",
        "Épicerie",
        "Epicerie fine",
        "Équipements du foyer",
        "Equipement sportif",
        "Ergothérapeute",
        "Espace collaboratif",
        "Espace numérique",
        "Espace vert et naturel",
        "Etablissement de prévention",
        "Établissement de santé",
        "Établissement militaire",
        "Etablissement pénitentiaire",
        "Établissement thermal",
        "Evénement culturel",
        "Fédération départementale pour la pêche et la protection du milieu aquatique",
        "Ferme",
        "Fleuriste",
        "Friperie",
        "Fruits et légumes",
        "Galerie d'art",
        "Garage automobile",
        "Garderie",
        "Gare routière",
        "Gare sncf",
        "Gare tgv",
        "Gastro-entérologie hépatologie",
        "Gendarmerie",
        "Géomètre",
        "Glacier",
        "Greffe des associations",
        "Guichet france services",
        "Gymnase",
        "Gynécologie",
        "Hébergement insolite",
        "Hématologie",
        "Herboristerie naturopathie",
        "Hôpital",
        "Horlogerie",
        "Hôtel",
        "Hôtel restaurant",
        "Huissier",
        "Hypermarché",
        "Hypnothérapeute",
        "Immobilier",
        "Imprimerie photocopie reliure",
        "Infirmier",
        "Information Touristique",
        "Informatique",
        "Institut de formation",
        "Instruments et matériel de musique",
        "Jardin botanique et/ou zoologique",
        "Jardinerie",
        "Jeux jouets",
        "Jeux vidéo",
        "Karaoké",
        "Kinésiologue",
        "Kiosque (théâtre, pizza, journaux)",
        "Laboratoire d'analyse médicale",
        "Laverie",
        "Librairie",
        "Lieu de culte",
        "Lieu de visite",
        "Lingerie sous-vêtements",
        "Literie",
        "Location articles loisirs et sport",
        "Location de matériels",
        "Location saisonnière",
        "Location véhicules",
        "Loisirs créatifs",
        "Luminaire",
        "Lycée",
        "Magasin de bois de chauffage",
        "Magasin de cbd",
        "Magasin de déguisements",
        "Magasin de souvenirs",
        "Magasin de tissus",
        "Mairie",
        "Maison départementale des personnes handicapées",
        "Maison de santé ou centre de santé",
        "Maison de services au public",
        "Marché",
        "Maroquinerie sellerie articles de voyage",
        "Massages",
        "Masseur kinésithérapeute",
        "Matériel de pêche",
        "Médecine du travail",
        "Médecin généraliste",
        "Menuiserie, ébénisterie",
        "Mercerie",
        "Meubles ameublement",
        "Mission d'accueil et d'information des associations",
        "Mission locale pour l'insertion professionnelle et sociale des jeunes",
        "Monument historique",
        "Motocycle vente et entretien",
        "Musée",
        "Musique",
        "Neurologie",
        "Notaire",
        "Numérique",
        "Oenotourisme",
        "Office du tourisme",
        "Opéra",
        "Ophtalmologie",
        "Opticien",
        "Ordre des avocats",
        "Organisation patronale, professionnelle, syndicale",
        "Organisme de conseil",
        "Orthodontie",
        "Orthopédie",
        "Orthophonie",
        "Orthoptie",
        "Ostéopathie",
        "Oto-rhino-laryngologie",
        "Papeterie, presse, journaux",
        "Parc",
        "Parc d’attraction",
        "Parc des expositions",
        "Parfumerie, cosmétique",
        "Parking & stationnement",
        "Patinoire",
        "Pédiatrie",
        "Pédicure-podologue",
        "Pépinière",
        "Personnes âgées : foyer restaurant",
        "Personnes âgées : hébergement",
        "Pharmacie",
        "Photographie",
        "Piscine, centre aquatique",
        "Plage, zone de baignade",
        "Plateaux et terrains de jeux extérieurs",
        "Plomberie, chauffage",
        "Pneumologie",
        "Point accueil numerique",
        "Point conseil budget",
        "Point d'information local dédié aux personnes âgées",
        "Point information jeunesse",
        "Point justice",
        "Poissonnerie / commerce de poissons, crustacés et mollusques",
        "Pompes funèbres",
        "Port",
        "Poterie verrerie céramique",
        "Pressing, nettoyage",
        "Primeur",
        "Produits de terroir",
        "Produits d'occasion",
        "Produits surgelés",
        "Profession libérale",
        "Psychologie, Psychiatrie",
        "Psychomotricien",
        "Puériculture",
        "Radiodiagnostic et imagerie médicale",
        "Refuge animalier",
        "Rempailleur tapissier chaises fauteuils",
        "Réparation auto et de matériel agricole",
        "Résidence de tourisme",
        "Résidence, foyer",
        "Ressourcerie",
        "Restaurant",
        "Restaurant scolaire",
        "Restauration rapide",
        "Retouche",
        "Revêtements murs et sols",
        "Rhumatologie",
        "Sage-femme",
        "Salle de combat",
        "Salle de concert",
        "Salle de danse",
        "Salle de jeux",
        "Salle de remise en forme",
        "Salle de réunion ou réception",
        "Salle des fêtes",
        "Salle de spectacle",
        "Salle multisports",
        "Salle non spécialisée",
        "Salle spécialisée",
        "Salon de thé",
        "Sécurité sociale, mutuelle santé",
        "Service ou aide à domicile",
        "Services techniques",
        "Sex shop",
        "Skatepark",
        "Soins de beauté, esthétique",
        "Sophrologue",
        "Spa",
        "Sports et loisirs",
        "Sports nautiques",
        "Stade",
        "Station lavage auto",
        "Station service",
        "Stomatologie",
        "Supérette",
        "Supermarché",
        "Syndic, gérance immo",
        "Tabac",
        "Tatouage Piercing",
        "Taxi",
        "Taxidermie",
        "Téléphonie",
        "Tennis",
        "Textile hors habillement",
        "Thalassothérapie",
        "Théâtre",
        "Tiers lieu",
        "Toilettes publiques",
        "Toiletteur",
        "Traiteur",
        "Transport",
        "Trésorerie",
        "Tribunal",
        "Université ou école supérieure",
        "Urologie",
        "Vente à distance",
        "Vente d'articles de sport",
        "Vente de cafés et thés",
        "Vente de matériel et équipement industriels",
        "Vente de matériel médical",
        "Vente de matériel pour piscine",
        "Vêtements",
        "Vétérinaire",
        "Village de vacances",
        "Vitrerie, miroiterie",
    ]

    group = ActivitiesGroup.objects.create(name="Hébergement")
    for name in list_activite:
        activity, created = Activite.objects.get_or_create(nom=name)
        if created and name in ("Hôtel", "Hôtel restaurant", "Chambres d'hôtes, gîte, pension"):
            group.activities.add(activity.pk)


@pytest.fixture
def akei_result():
    return dict(
        source="entreprise_api",
        source_id="12345",
        coordonnees=None,
        naf="62.02A",
        activite=None,
        nom="AKEI",
        siret="88076068100010",
        numero="4",
        voie="GRAND RUE",
        lieu_dit=None,
        code_postal="34830",
        commune="JACOU",
        code_insee="34120",
        contact_email=None,
        telephone=None,
        site_internet=None,
    )


@pytest.fixture
def mairie_jacou_result():
    return dict(
        source="public_erp",
        source_id="mairie-jacou-34120-01",
        coordonnees=[3, 42],
        naf=None,
        activite=None,
        nom="Mairie - Jacou",
        siret=None,
        numero="2",
        voie="Place de la Mairie",
        lieu_dit=None,
        code_postal="34830",
        commune="Jacou",
        code_insee="34120",
        contact_email="jacou@jacou.fr",
        telephone="01 02 03 04 05",
        site_internet="https://ville-jacou.fr/",
    )


register(ErpFactory)
register(AccessibiliteFactory)
register(UserFactory)
