ACTIVITES = [
    "Antiquaire",
    "Accessoires",
    "Administration publique",
    "Aéroport",
    "Agence de travail temporaire",
    "Agence de voyage",
    "Agence immobilière",
    "Agence postale ",
    "Aide sociale à l'enfance : action éducative",
    "Aménagement maison : cuisine salle de bain salon",
    "Animalerie",
    "Architecte",
    "Armurerie coutellerie",
    "Art",
    "Assurance",
    "Athlétisme",
    "Audio prothésiste",
    "Auto école",
    "Autres établissements pour adultes et familles en difficulté",
    "Avocat",
    "Banques, caisses d'épargne",
    "Bibliothèque médiathèque",
    "Bijouterie joaillerie",
    "Blanchisserie teinturerie",
    "Boucherie ",
    "Boulangerie",
    "Boulodrome",
    "Bouquins",
    "Bowling",
    "Bricolage aménagement",
    "Bureau de poste",
    "Café et thés",
    "Cafétéria",
    "Camping caravaning",
    "Cantine",
    "Cardiologie",
    "Carrosserie",
    "Caviste",
    "Centre commercial",
    "Centre de loisirs",
    "Centre de vacances",
    "Centre équestre",
    "Centre religieux",
    "Chapeaux et couvre-chefs",
    "Charcuterie",
    "Chaussures",
    "Chirurgien dentiste",
    "Chocolatier",
    "Cigarette électronique",
    "Cimetière",
    "Cinéma ",
    "Clinique",
    "Coiffure",
    "Collège",
    "Commerce automobile",
    "Comptable expert-comptable",
    "Confiserie",
    "Conservatoire",
    "Contrôle technique auto",
    "Cordonnerie serrurerie",
    "Crèmerie Fromagerie",
    "Cure thermale",
    "Cycle vente et entretien",
    "Cyclisme",
    "Débit de boisson",
    "Décoration Design",
    "Dermatologie vénéréologie",
    "Disquaire",
    "Droguerie quincaillerie bricolage",
    "École de conduite",
    "École élémentaire",
    "École maternelle",
    "Électroménager et matériel audio-vidéo",
    "Empailleur Taxidermiste",
    "Encadreur enlumineur",
    "Épicerie",
    "Équipements du foyer",
    "Ergothérapeute",
    "Établissement de santé ",
    "Exploitation agricole",
    "Fleuriste",
    "Fruits et légumes",
    "Garage",
    "Gare avec desserte train à grande vitesse (TAGV)",
    "Gare routière",
    "Gare sans desserte train à grande vitesse (TAGV)",
    "Gastro-entérologie hépatologie",
    "Glacier",
    "Gymnase",
    "Gynécologie médicale",
    "Gynécologie obstétrique",
    "Herboristerie naturopathie",
    "Hôpital",
    "Horlogerie",
    "Hôtel",
    "Huissier",
    "Hypermarché",
    "Imprimerie photocopie reliure",
    "Infirmier",
    "Information Touristique",
    "Informatique",
    "Instruments et matériel de musique",
    "Jardin botanique et/ou zoologique",
    "Jardinerie",
    "Jeux jouets",
    "Juriste",
    "Laverie",
    "Librairie ",
    "Lieu de culte",
    "Linge maison",
    "Literie",
    "Location articles loisirs et sport",
    "Location véhicules",
    "Luminaire",
    "Lycée",
    "Mairie",
    "Maison de santé ou centre de santé",
    "Maroquinerie sellerie articles de voyage",
    "Massages",
    "Masseur kinésithérapeute",
    "Médecin généraliste",
    "Mercerie",
    "Meubles ameublement",
    "Motocycle vente et entretien",
    "Musée",
    "Notaire",
    "Ophtalmologie",
    "Optique",
    "Organisation patronale, professionnelle, syndicale",
    "Orthopédie",
    "Orthophonie",
    "Orthoptie",
    "Oto-rhino-laryngologie",
    "Papeterie journaux ",
    "Parc d’attraction et parc à thème",
    "Parfumerie produits de beauté",
    "Patinoire",
    "Pâtisserie",
    "Pédiatrie",
    "Pédicure-podologue",
    "Pension gîte",
    "Personnes âgées : foyer restaurant",
    "Personnes âgées : hébergement",
    "Petite enfance crèche",
    "Pharmacie",
    "Photographie",
    "Piscine",
    "Plateaux et terrains de jeux extérieurs",
    "Pneumologie",
    "Poissonnerie",
    "Pompes funèbres",
    "Port",
    "Poterie verrerie céramique",
    "Produits surgelés",
    "Profession libérale",
    "Promotion immobilière",
    "Psychiatrie",
    "Psychomotricien",
    "Radiodiagnostic et imagerie médicale",
    "Relais poste ",
    "Rempailleur chaises fauteuils",
    "Réparation auto et de matériel agricole",
    "Restaurant",
    "Restaurant scolaire",
    "Restauration rapide",
    "Retouche",
    "Revêtements murs et sols",
    "Roller-Skate-Vélo bicross ou freestyle",
    "Sage-femme",
    "Salle de combat",
    "salle de danse",
    "Salle de jeux",
    "Salle de spectacle",
    "Salle multisports",
    "Salle non spécialisée",
    "Salle spécialisée",
    "Salles de remise en forme",
    "Salon de thé",
    "Service à domicile",
    "Sex shop",
    "Soins de beauté",
    "Spa",
    "Sports et loisirs",
    "Sports nautiques",
    "Stade",
    "Station lavage auto",
    "Station service",
    "Stomatologie",
    "Supérette",
    "Supermarché",
    "Tabac",
    "Tatouage Piercing",
    "Téléphonie",
    "Tennis",
    "Textile hors habillement",
    "Théâtre",
    "Toiletteur",
    "Traiteur",
    "Université ou école supérieure",
    "Vêtements sous-vêtements lingerie",
    "Vétérinaire",
]
