# Generated by Django 3.0.2 on 2020-01-31 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom de l'activité", max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='erp',
            old_name='cpost',
            new_name='code_postal',
        ),
        migrations.RenameField(
            model_name='erp',
            old_name='cplt',
            new_name='complement',
        ),
        migrations.RenameField(
            model_name='erp',
            old_name='num',
            new_name='numero',
        ),
        migrations.RemoveField(
            model_name='erp',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='erp',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='erp',
            name='date',
        ),
        migrations.RemoveField(
            model_name='erp',
            name='demandeur',
        ),
        migrations.RemoveField(
            model_name='erp',
            name='derog',
        ),
        migrations.RemoveField(
            model_name='erp',
            name='domaine',
        ),
        migrations.RemoveField(
            model_name='erp',
            name='dossier',
        ),
        migrations.RemoveField(
            model_name='erp',
            name='duree',
        ),
        migrations.RemoveField(
            model_name='erp',
            name='gid',
        ),
        migrations.RemoveField(
            model_name='erp',
            name='id_adap',
        ),
        migrations.RemoveField(
            model_name='erp',
            name='nature',
        ),
        migrations.RemoveField(
            model_name='erp',
            name='objet_dero',
        ),
        migrations.RemoveField(
            model_name='erp',
            name='precision',
        ),
        migrations.RemoveField(
            model_name='erp',
            name='qualite',
        ),
        migrations.RemoveField(
            model_name='erp',
            name='type',
        ),
        migrations.AddField(
            model_name='erp',
            name='activite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.Activite'),
        ),
    ]
