# Generated by Django 3.0.2 on 2020-01-31 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0002_auto_20200131_1536"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activite",
            old_name="name",
            new_name="nom",
        ),
    ]
