# Generated by Django 3.0.2 on 2020-01-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0004_auto_20200131_1607"),
    ]

    operations = [
        migrations.AlterField(
            model_name="erp",
            name="lat",
            field=models.FloatField(blank=True, help_text="Latitude", null=True),
        ),
        migrations.AlterField(
            model_name="erp",
            name="lon",
            field=models.FloatField(blank=True, help_text="Longitude", null=True),
        ),
    ]
