# Generated by Django 3.0.2 on 2020-01-31 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0007_erp_geom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="erp",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="erp",
            name="lon",
        ),
    ]
