# Generated by Django 3.0.2 on 2020-02-03 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0008_auto_20200131_2305"),
    ]

    operations = [
        migrations.CreateModel(
            name="Circulation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reperage_vitres",
                    models.BooleanField(
                        blank=True,
                        help_text="Présence d'un repérage sur les surfaces vitrées",
                        null=True,
                    ),
                ),
                (
                    "bande_guidage",
                    models.BooleanField(
                        blank=True,
                        help_text="Présence d'une bande de guidage",
                        null=True,
                    ),
                ),
                (
                    "guidage_sonore",
                    models.BooleanField(
                        blank=True,
                        help_text="Présence d'un dispositif de guidage sonore",
                        null=True,
                    ),
                ),
                (
                    "largeur_mini",
                    models.IntegerField(
                        blank=True,
                        help_text="Largeur minimale de la circulation",
                        null=True,
                    ),
                ),
                (
                    "pente",
                    models.CharField(
                        blank=True,
                        choices=[("légère", "Légère"), ("importante", "Importante")],
                        help_text="Présence et type de pente",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "devers",
                    models.CharField(
                        blank=True,
                        choices=[("léger", "Léger"), ("important", "Important")],
                        help_text="Présence et type de dévers",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "rampe",
                    models.CharField(
                        blank=True,
                        choices=[("fixe", "Fixe"), ("amovible", "Amovible")],
                        help_text="Présence et type d'une rampe",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "escalier_marches",
                    models.IntegerField(
                        blank=True,
                        help_text="Nombre de marches d'escalier, si applicable",
                        null=True,
                    ),
                ),
                (
                    "escalier_main_courante",
                    models.BooleanField(
                        blank=True,
                        help_text="Présence d'une main courante d'escalier",
                        null=True,
                    ),
                ),
                (
                    "ascenseur",
                    models.BooleanField(
                        blank=True,
                        help_text="Présence d'un ascenseur ou d'un élévateur",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Accessibilite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("presence", models.BooleanField(blank=True, null=True)),
                ("reserve_pmr", models.BooleanField(blank=True, null=True)),
                (
                    "entree_signaletique",
                    models.BooleanField(
                        blank=True,
                        help_text="Présence d'une signalétique matérialisant l'entrée",
                        null=True,
                    ),
                ),
                (
                    "entree_secondaire",
                    models.BooleanField(
                        blank=True,
                        help_text="Présence d'une entrée secondaire",
                        null=True,
                    ),
                ),
                (
                    "entree_secondaire_informations",
                    models.TextField(
                        blank=True,
                        help_text="Précisions sur les modalités d'accès de l'entrée secondaire",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "accueil_personnels",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("formés", "Personnels formés"),
                            ("non-formés", "Personnels non-formés"),
                        ],
                        help_text="Présence et type de personnels d'accueil",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "accueil_lsf",
                    models.BooleanField(blank=True, help_text="Présence d'équipements LSF", null=True),
                ),
                (
                    "accueil_bim",
                    models.BooleanField(blank=True, help_text="Présence d'équipements BIM", null=True),
                ),
                (
                    "accueil_prestations",
                    models.TextField(
                        blank=True,
                        help_text="Description libre des prestations adaptées",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "sanitaires_presence",
                    models.BooleanField(
                        blank=True,
                        help_text="Présence de sanitaires dans l'établissement",
                        null=True,
                    ),
                ),
                (
                    "sanitaires_adaptes",
                    models.IntegerField(
                        blank=True,
                        help_text="Nombre de sanitaires adaptés dans l'établissement",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cheminement_entree_accueil",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cheminement de l'entrée du bâtiment à l'accueil",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessibilite_cheminement_entree_accueil",
                        to="erp.Circulation",
                    ),
                ),
                (
                    "cheminement_parcelle_entree",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cheminement depuis l'entrée de la parcelle de terrain à l'entrée du bâtiment",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessibilite_cheminement_parcelle_entree",
                        to="erp.Circulation",
                    ),
                ),
                (
                    "cheminement_place_entree",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cheminement du stationnement à l'entrée du bâtiment",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessibilite_cheminement_place_entree",
                        to="erp.Circulation",
                    ),
                ),
                (
                    "cheminement_stationnement",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cheminement depuis le stationnement de l'ERP",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessibilite_cheminement_stationnement",
                        to="erp.Circulation",
                    ),
                ),
                (
                    "cheminement_stationnement_ext",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cheminement depuis le stationnement extérieur à l'ERP",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessibilite_cheminement_stationnement_ext",
                        to="erp.Circulation",
                    ),
                ),
                (
                    "entree_circulation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Caractéristiques d'accessibilité de l'entrée principale",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessibilite_entree",
                        to="erp.Circulation",
                    ),
                ),
                ("labels", models.ManyToManyField(to="erp.Label")),
            ],
        ),
        migrations.AddField(
            model_name="erp",
            name="accessibilite",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="erp.Accessibilite",
            ),
        ),
    ]
