# Generated by Django 3.0.3 on 2020-02-03 12:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0010_auto_20200203_1159"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accessibilite",
            name="presence",
        ),
        migrations.RemoveField(
            model_name="accessibilite",
            name="reserve_pmr",
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="stationnement_pmr",
            field=models.BooleanField(
                blank=True,
                help_text="Présence de stationnements adaptés à proximité",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="stationnement_presence",
            field=models.BooleanField(blank=True, help_text="Présence de stationnement à proximité", null=True),
        ),
        migrations.AlterField(
            model_name="circulation",
            name="reperage_vitres",
            field=models.BooleanField(
                blank=True,
                help_text="Présence d'un repérage sur les surfaces vitrées",
                null=True,
                verbose_name="Répérage surfaces vitrées",
            ),
        ),
        migrations.AlterField(
            model_name="erp",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326, verbose_name="Localisation"
            ),
        ),
    ]
