# Generated by Django 3.0.3 on 2020-02-03 13:44

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0011_auto_20200203_1345"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="erp",
            name="complement",
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date de création"),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Dernière modification"),
        ),
        migrations.AlterField(
            model_name="activite",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date de création"),
        ),
        migrations.AlterField(
            model_name="activite",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Dernière modification"),
        ),
        migrations.AlterField(
            model_name="circulation",
            name="ascenseur",
            field=models.BooleanField(
                blank=True,
                help_text="Présence d'un ascenseur ou d'un élévateur",
                null=True,
                verbose_name="Ascenseur/élévateur",
            ),
        ),
        migrations.AlterField(
            model_name="circulation",
            name="bande_guidage",
            field=models.BooleanField(
                blank=True,
                help_text="Présence d'une bande de guidage",
                null=True,
                verbose_name="Bande de guidage",
            ),
        ),
        migrations.AlterField(
            model_name="circulation",
            name="devers",
            field=models.CharField(
                blank=True,
                choices=[("léger", "Léger"), ("important", "Important")],
                help_text="Présence et type de dévers",
                max_length=15,
                null=True,
                verbose_name="Dévers",
            ),
        ),
        migrations.AlterField(
            model_name="circulation",
            name="escalier_main_courante",
            field=models.BooleanField(
                blank=True,
                help_text="Présence d'une main courante d'escalier",
                null=True,
                verbose_name="Main courante",
            ),
        ),
        migrations.AlterField(
            model_name="circulation",
            name="escalier_marches",
            field=models.IntegerField(
                blank=True,
                help_text="Nombre de marches d'escalier, si applicable",
                null=True,
                verbose_name="Marches d'escalier",
            ),
        ),
        migrations.AlterField(
            model_name="circulation",
            name="guidage_sonore",
            field=models.BooleanField(
                blank=True,
                help_text="Présence d'un dispositif de guidage sonore",
                null=True,
                verbose_name="Système de guidage sonore",
            ),
        ),
        migrations.AlterField(
            model_name="circulation",
            name="largeur_mini",
            field=models.IntegerField(
                blank=True,
                help_text="Largeur minimale du passage, en centimètres",
                null=True,
                verbose_name="Largeur minimale",
            ),
        ),
        migrations.AlterField(
            model_name="erp",
            name="activite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="erp.Activite",
                verbose_name="Activité",
            ),
        ),
        migrations.AlterField(
            model_name="erp",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date de création"),
        ),
        migrations.AlterField(
            model_name="erp",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Localisation du bâtiment",
                null=True,
                srid=4326,
                verbose_name="Localisation",
            ),
        ),
        migrations.AlterField(
            model_name="erp",
            name="numero",
            field=models.CharField(
                blank=True,
                help_text="Numéro dans la voie, incluant le complément (BIS, TER, etc.)",
                max_length=12,
                null=True,
                verbose_name="Numéro",
            ),
        ),
        migrations.AlterField(
            model_name="erp",
            name="siret",
            field=models.CharField(
                blank=True,
                help_text="Numéro SIRET si l'ERP est une entreprise",
                max_length=255,
                null=True,
                verbose_name="SIRET",
            ),
        ),
        migrations.AlterField(
            model_name="erp",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Dernière modification"),
        ),
        migrations.AlterField(
            model_name="label",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date de création"),
        ),
        migrations.AlterField(
            model_name="label",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Dernière modification"),
        ),
    ]
