# Generated by Django 3.0.3 on 2020-02-03 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_auto_20200203_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessibilite',
            name='cheminement_entree_accueil',
            field=models.OneToOneField(blank=True, help_text="Cheminement de l'entrée du bâtiment à l'accueil", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessibilite_cheminement_entree_accueil', to='erp.Circulation'),
        ),
        migrations.AlterField(
            model_name='accessibilite',
            name='cheminement_parcelle_entree',
            field=models.OneToOneField(blank=True, help_text="Cheminement depuis l'entrée de la parcelle de terrain à l'entrée du bâtiment", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessibilite_cheminement_parcelle_entree', to='erp.Circulation'),
        ),
        migrations.AlterField(
            model_name='accessibilite',
            name='cheminement_place_entree',
            field=models.OneToOneField(blank=True, help_text="Cheminement du stationnement à l'entrée du bâtiment", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessibilite_cheminement_place_entree', to='erp.Circulation'),
        ),
        migrations.AlterField(
            model_name='accessibilite',
            name='cheminement_stationnement',
            field=models.OneToOneField(blank=True, help_text="Cheminement depuis le stationnement de l'ERP", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessibilite_cheminement_stationnement', to='erp.Circulation'),
        ),
        migrations.AlterField(
            model_name='accessibilite',
            name='cheminement_stationnement_ext',
            field=models.OneToOneField(blank=True, help_text="Cheminement depuis le stationnement extérieur à l'ERP", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessibilite_cheminement_stationnement_ext', to='erp.Circulation'),
        ),
        migrations.AlterField(
            model_name='accessibilite',
            name='entree_circulation',
            field=models.OneToOneField(blank=True, help_text="Caractéristiques d'accessibilité de l'entrée principale", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessibilite_entree', to='erp.Circulation'),
        ),
    ]
