# Generated by Django 3.0.3 on 2020-02-03 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0013_auto_20200203_1506"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cheminement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (
                                "stationnement_vers_erp",
                                "Cheminement depuis le stationnement de l'ERP",
                            ),
                            (
                                "stationnement_ext_vers_erp",
                                "Cheminement depuis le stationnement extérieur à l'ERP",
                            ),
                            (
                                "stationnement_vers_entree",
                                "Cheminement du stationnement à l'entrée du bâtiment",
                            ),
                            (
                                "parcelle_vers_entree",
                                "Cheminement depuis l'entrée de la parcelle de terrain à l'entrée du bâtiment",
                            ),
                            (
                                "entree_vers_accueil",
                                "Cheminement de l'entrée du bâtiment à l'accueil",
                            ),
                            ("entree", "Cheminement autour de l'entrée"),
                        ],
                        default="entree",
                        help_text="Type de cheminement",
                        max_length=100,
                        verbose_name="Cheminement",
                    ),
                ),
                (
                    "reperage_vitres",
                    models.BooleanField(
                        blank=True,
                        help_text="Présence d'un repérage sur les surfaces vitrées",
                        null=True,
                        verbose_name="Répérage surfaces vitrées",
                    ),
                ),
                (
                    "bande_guidage",
                    models.BooleanField(
                        blank=True,
                        help_text="Présence d'une bande de guidage",
                        null=True,
                        verbose_name="Bande de guidage",
                    ),
                ),
                (
                    "guidage_sonore",
                    models.BooleanField(
                        blank=True,
                        help_text="Présence d'un dispositif de guidage sonore",
                        null=True,
                        verbose_name="Système de guidage sonore",
                    ),
                ),
                (
                    "largeur_mini",
                    models.IntegerField(
                        blank=True,
                        help_text="Largeur minimale du passage, en centimètres",
                        null=True,
                        verbose_name="Largeur minimale",
                    ),
                ),
                (
                    "pente",
                    models.CharField(
                        blank=True,
                        choices=[("légère", "Légère"), ("importante", "Importante")],
                        help_text="Présence et type de pente",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "devers",
                    models.CharField(
                        blank=True,
                        choices=[("léger", "Léger"), ("important", "Important")],
                        help_text="Présence et type de dévers",
                        max_length=15,
                        null=True,
                        verbose_name="Dévers",
                    ),
                ),
                (
                    "rampe",
                    models.CharField(
                        blank=True,
                        choices=[("fixe", "Fixe"), ("amovible", "Amovible")],
                        help_text="Présence et type d'une rampe",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "escalier_marches",
                    models.IntegerField(
                        blank=True,
                        help_text="Nombre de marches d'escalier, si applicable",
                        null=True,
                        verbose_name="Marches d'escalier",
                    ),
                ),
                (
                    "escalier_main_courante",
                    models.BooleanField(
                        blank=True,
                        help_text="Présence d'une main courante d'escalier",
                        null=True,
                        verbose_name="Main courante",
                    ),
                ),
                (
                    "ascenseur",
                    models.BooleanField(
                        blank=True,
                        help_text="Présence d'un ascenseur ou d'un élévateur",
                        null=True,
                        verbose_name="Ascenseur/élévateur",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="accessibilite",
            name="cheminement_entree_accueil",
        ),
        migrations.RemoveField(
            model_name="accessibilite",
            name="cheminement_parcelle_entree",
        ),
        migrations.RemoveField(
            model_name="accessibilite",
            name="cheminement_place_entree",
        ),
        migrations.RemoveField(
            model_name="accessibilite",
            name="cheminement_stationnement",
        ),
        migrations.RemoveField(
            model_name="accessibilite",
            name="cheminement_stationnement_ext",
        ),
        migrations.RemoveField(
            model_name="accessibilite",
            name="entree_circulation",
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="stationnement_pmr",
            field=models.BooleanField(
                blank=True,
                help_text="Présence de stationnements adaptés à proximité",
                null=True,
                verbose_name="Stationnements PMR",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="stationnement_presence",
            field=models.BooleanField(
                blank=True,
                help_text="Présence de stationnement à proximité",
                null=True,
                verbose_name="Stationnement",
            ),
        ),
        migrations.DeleteModel(
            name="Circulation",
        ),
        migrations.AddField(
            model_name="cheminement",
            name="accessibilite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="erp.Accessibilite"
            ),
        ),
    ]
