# Generated by Django 3.0.3 on 2020-02-04 07:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0014_auto_20200203_1646"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_sous_titrage",
            field=models.BooleanField(
                blank=True,
                help_text="Présence d'équipements de sous-titrage",
                null=True,
                verbose_name="Sous-titrage",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="entree_interphone",
            field=models.BooleanField(
                blank=True,
                help_text="Présence d'un dispositif d'appel (ex. interphone)",
                null=True,
                verbose_name="Dispositif d'appel",
            ),
        ),
        migrations.AddField(
            model_name="cheminement",
            name="escalier_reperage",
            field=models.BooleanField(
                blank=True,
                help_text="Repérage visuel des marches d'escalier",
                null=True,
                verbose_name="Repérage des marches",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="accueil_bim",
            field=models.BooleanField(
                blank=True,
                help_text="Présence d'équipements BIM",
                null=True,
                verbose_name="BIM",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="accueil_lsf",
            field=models.BooleanField(
                blank=True,
                help_text="Présence d'équipements LSF",
                null=True,
                verbose_name="LSF",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="accueil_personnels",
            field=models.CharField(
                blank=True,
                choices=[
                    ("formés", "Personnels formés"),
                    ("non-formés", "Personnels non-formés"),
                ],
                help_text="Présence et type de personnels d'accueil",
                max_length=255,
                null=True,
                verbose_name="Personnel d'accueil",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="accueil_prestations",
            field=models.TextField(
                blank=True,
                help_text="Description libre des prestations adaptées",
                max_length=1000,
                null=True,
                verbose_name="Prestations d'accueil",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="entree_secondaire",
            field=models.BooleanField(
                blank=True,
                help_text="Présence d'une entrée secondaire",
                null=True,
                verbose_name="Entrée secondaire",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="entree_secondaire_informations",
            field=models.TextField(
                blank=True,
                help_text="Précisions sur les modalités d'accès de l'entrée secondaire",
                max_length=500,
                null=True,
                verbose_name="Infos entrée secondaire",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="entree_signaletique",
            field=models.BooleanField(
                blank=True,
                help_text="Présence d'une signalétique matérialisant l'entrée",
                null=True,
                verbose_name="Signalétique à l'entrée",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="sanitaires_adaptes",
            field=models.IntegerField(
                blank=True,
                help_text="Nombre de sanitaires adaptés dans l'établissement",
                null=True,
                verbose_name="Nombre de sanitaires adaptés",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="sanitaires_presence",
            field=models.BooleanField(
                blank=True,
                help_text="Présence de sanitaires dans l'établissement",
                null=True,
                verbose_name="Sanitaires",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="stationnement_presence",
            field=models.BooleanField(
                blank=True,
                help_text="Présence de stationnements à proximité",
                null=True,
                verbose_name="Stationnement",
            ),
        ),
        migrations.AlterField(
            model_name="cheminement",
            name="largeur_mini",
            field=models.IntegerField(
                blank=True,
                help_text="Largeur minimale du passage ou rétrécissement, en centimètres",
                null=True,
                verbose_name="Largeur minimale",
            ),
        ),
        migrations.AlterField(
            model_name="cheminement",
            name="rampe",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fixe", "Fixe"),
                    ("amovible", "Amovible"),
                    ("aide humaine", "Aide humaine"),
                ],
                help_text="Présence et type d'une rampe",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="erp",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Géolocalisation opérée à partir de l'adresse une fois l'enregistrement sauvegardé",
                null=True,
                srid=4326,
                verbose_name="Localisation",
            ),
        ),
    ]
