# Generated by Django 3.0.3 on 2020-02-04 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_auto_20200204_0833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessibilite',
            options={'verbose_name': 'Accessibilité', 'verbose_name_plural': 'Accessibilités'},
        ),
        migrations.AlterModelOptions(
            name='activite',
            options={'verbose_name': 'Activité', 'verbose_name_plural': 'Activités'},
        ),
        migrations.AlterModelOptions(
            name='erp',
            options={'verbose_name': 'Établissement', 'verbose_name_plural': 'Établissements'},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': "Label d'accessibilité", 'verbose_name_plural': "Labels d'accessibilité"},
        ),
    ]
