# Generated by Django 3.0.3 on 2020-02-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_auto_20200204_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessibilite',
            name='accueil_personnels',
            field=models.CharField(blank=True, choices=[('aucun', 'Aucun personnel'), ('formés', 'Personnels formés'), ('non-formés', 'Personnels non-formés')], help_text="Présence et type de personnels d'accueil", max_length=255, null=True, verbose_name="Personnel d'accueil"),
        ),
        migrations.AlterField(
            model_name='cheminement',
            name='rampe',
            field=models.CharField(blank=True, choices=[('aucune', 'Aucune'), ('fixe', 'Fixe'), ('amovible', 'Amovible'), ('aide humaine', 'Aide humaine')], help_text="Présence et type d'une rampe", max_length=20, null=True),
        ),
    ]
