# Generated by Django 3.0.3 on 2020-02-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0020_auto_20200205_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessibilite',
            name='accueil_equipements_malentendants',
            field=models.ManyToManyField(blank=True, help_text='Choix multiple possible (maintenez la touche Ctrl enfoncée pour sélectionner plusieurs entrées)', to='erp.EquipementMalentendant', verbose_name='Équipements sourds/malentendants'),
        ),
        migrations.AlterField(
            model_name='accessibilite',
            name='labels',
            field=models.ManyToManyField(blank=True, help_text="Labels d'accessibilité obtenus par l'ERP (maintenez la touche Ctrl enfoncée pour sélectionner plusieurs entrées)", to='erp.Label'),
        ),
    ]
