# Generated by Django 3.0.3 on 2020-02-05 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0021_auto_20200205_0825"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accessibilite",
            old_name="entree_secondaire_informations",
            new_name="entree_pmr_informations",
        ),
    ]
