# Generated by Django 3.0.3 on 2020-02-05 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0022_auto_20200205_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessibilite',
            old_name='entree_signaletique',
            new_name='entree_reperage',
        ),
    ]
