# Generated by Django 3.0.3 on 2020-02-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0024_auto_20200205_0837"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessibilite",
            name="sanitaires_adaptes",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Nombre de sanitaires adaptés dans l'établissement",
                null=True,
                verbose_name="Nombre de sanitaires adaptés",
            ),
        ),
        migrations.AlterField(
            model_name="cheminement",
            name="escalier_marches",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Nombre de marches d'escalier, si applicable",
                null=True,
                verbose_name="Marches d'escalier",
            ),
        ),
        migrations.AlterField(
            model_name="cheminement",
            name="largeur_mini",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Largeur minimale du passage ou rétrécissement, en centimètres",
                null=True,
                verbose_name="Largeur minimale",
            ),
        ),
    ]
