# Generated by Django 3.0.3 on 2020-02-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0026_auto_20200205_0950"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cheminement",
            options={
                "verbose_name": "Circulation",
                "verbose_name_plural": "Circulations",
            },
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="accueil_personnels",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "Inconnu"),
                    ("aucun", "Aucun personnel"),
                    ("formés", "Personnels sensibilisés et formés"),
                    ("non-formés", "Personnels non-formés"),
                ],
                help_text="Présence et type de personnel d'accueil",
                max_length=255,
                null=True,
                verbose_name="Personnel d'accueil",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="stationnement_ext_pmr",
            field=models.BooleanField(
                blank=True,
                help_text="Présence de stationnements PMR à proximité (200m)",
                null=True,
                verbose_name="Stationnements PMR à proximité",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="stationnement_pmr",
            field=models.BooleanField(
                blank=True,
                help_text="Présence de stationnements PMR au sein de l'ERP",
                null=True,
                verbose_name="Stationnements PMR dans l'ERP",
            ),
        ),
        migrations.AlterField(
            model_name="cheminement",
            name="escalier_marches",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Nombre de marches d'escalier. Indiquez 0 si pas d'escalier ou si présence d'un ascenseur/élévateur.",
                null=True,
                verbose_name="Marches d'escalier",
            ),
        ),
        migrations.AlterField(
            model_name="cheminement",
            name="escalier_reperage",
            field=models.BooleanField(
                blank=True,
                help_text="Si marches contrastées, bande d'éveil ou nez de marche contrastés, indiquez “Oui”",
                null=True,
                verbose_name="Repérage de l'escalier",
            ),
        ),
        migrations.AlterField(
            model_name="cheminement",
            name="type",
            field=models.CharField(
                choices=[
                    (
                        "ext_stationnement_vers_entree",
                        "Cheminement extérieur de la place de stationnement de l'ERP à l'entrée",
                    ),
                    (
                        "ext_entree_parcelle_entree_vers_batiment",
                        "Cheminement extérieur de l'entrée de la parcelle de terrain à l'entrée du bâtiment",
                    ),
                    (
                        "int_entree_batiment_vers_accueil",
                        "Cheminement intérieur de l'entrée du bâtiment jusqu'à l'accueil",
                    ),
                    ("entree", "Accessibilité de l'entrée"),
                ],
                default="entree",
                help_text="Type de cheminement",
                max_length=100,
                verbose_name="Cheminement",
            ),
        ),
        migrations.AlterField(
            model_name="erp",
            name="nom",
            field=models.CharField(
                help_text="Nom de l'établissement ou de l'enseigne", max_length=255
            ),
        ),
    ]
