# Generated by Django 3.0.3 on 2020-02-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_auto_20200205_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erp',
            name='voie',
            field=models.CharField(blank=True, help_text='Voie', max_length=255, null=True),
        ),
    ]
