# Generated by Django 3.0.3 on 2020-02-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0029_auto_20200205_1130"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cheminement",
            unique_together={("accessibilite", "type")},
        ),
    ]
