# Generated by Django 3.0.3 on 2020-02-05 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0030_auto_20200205_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activite',
            options={'ordering': ['nom'], 'verbose_name': 'Activité', 'verbose_name_plural': 'Activités'},
        ),
        migrations.AlterModelOptions(
            name='equipementmalentendant',
            options={'ordering': ['nom'], 'verbose_name': 'Équipement sourd/malentendant', 'verbose_name_plural': 'Équipements sourd/malentendant'},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['nom'], 'verbose_name': "Label d'accessibilité", 'verbose_name_plural': "Labels d'accessibilité"},
        ),
    ]
