# Generated by Django 3.0.3 on 2020-02-06 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0034_accessibilite_entree_plain_pied"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activite",
            options={
                "ordering": ("nom",),
                "verbose_name": "Activité",
                "verbose_name_plural": "Activités",
            },
        ),
        migrations.AlterModelOptions(
            name="equipementmalentendant",
            options={
                "ordering": ("nom",),
                "verbose_name": "Équipement sourd/malentendant",
                "verbose_name_plural": "Équipements sourd/malentendant",
            },
        ),
        migrations.AlterModelOptions(
            name="label",
            options={
                "ordering": ("nom",),
                "verbose_name": "Label d'accessibilité",
                "verbose_name_plural": "Labels d'accessibilité",
            },
        ),
        migrations.AlterField(
            model_name="erp",
            name="activite",
            field=models.ForeignKey(
                blank=True,
                help_text="Domaine d'activité de l'ERP. Attention, la recherche se fait sur les lettres accentuées",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="erp.Activite",
                verbose_name="Activité",
            ),
        ),
    ]
