# Generated by Django 3.0.3 on 2020-02-06 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0035_auto_20200206_1109"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="erp",
            options={
                "ordering": ("nom",),
                "verbose_name": "Établissement",
                "verbose_name_plural": "Établissements",
            },
        ),
    ]
