# Generated by Django 3.0.3 on 2020-02-12 15:26

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0037_erp_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="activite",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="generic", editable=False, populate_from="nom"
            ),
            preserve_default=False,
        ),
    ]
