# Generated by Django 3.0.3 on 2020-02-12 15:41

import autoslug.fields
from django.db import migrations


def migrate_data_forward(apps, schema_editor):
    Activite = apps.get_model("erp", "Activite")
    db_alias = schema_editor.connection.alias
    for instance in Activite.objects.all():
        print(f"Generating slug for {instance}")
        # forcing django model update
        nom = instance.nom
        instance.nom = nom + " "
        instance.save()
        instance.nom = nom
        instance.save()


def migrate_data_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0038_activite_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activite",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="generic",
                editable=False,
                null=True,
                populate_from="nom",
            ),
        ),
        migrations.RunPython(migrate_data_forward, migrate_data_backward,),
    ]
