# Generated by Django 3.0.3 on 2020-02-17 12:36

from django.contrib.postgres.operations import (
    TrigramExtension,
    UnaccentExtension,
)
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0041_auto_20200217_1208"),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
    ]
