# Generated by Django 3.0.3 on 2020-02-17 13:06

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0042_auto_20200217_1336"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="erp",
            index=django.contrib.postgres.indexes.GinIndex(fields=["nom"], name="nom_trgm", opclasses=["gin_trgm_ops"]),
        ),
    ]
