# Generated by Django 3.0.3 on 2020-02-26 11:34

from django.db import migrations, models


def migrate_cheminement_types(apps, schema_editor):
    Cheminement = apps.get_model("erp", "Cheminement")
    for cheminement in Cheminement.objects.all():
        if cheminement.type == "int_entree_batiment_vers_accueil":
            cheminement.type = "int"
            cheminement.nom = (
                "Cheminement intérieur de l'entrée du bâtiment jusqu'à l'accueil"
            )
        elif cheminement.type == "ext_stationnement_vers_entree":
            cheminement.type = "ext"
            cheminement.nom = (
                "Cheminement extérieur de la place de stationnement de l'ERP à l'entrée"
            )
        elif cheminement.type == "ext_entree_parcelle_entree_vers_batiment":
            cheminement.type = "ext"
            cheminement.nom = "Cheminement extérieur de l'entrée de la parcelle de terrain à l'entrée du bâtiment"
        cheminement.save()


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0045_auto_20200220_1643"),
    ]

    operations = [
        migrations.AddField(
            model_name="cheminement",
            name="nom",
            field=models.CharField(
                default="Cheminement indéterminé",
                help_text="Nom du cheminement, d'un point vers un autre (ex. Du stationnement à l'entrée de l'ERP)",
                max_length=255,
                verbose_name="Dénomination du cheminement",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cheminement",
            unique_together={("accessibilite", "type", "nom")},
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="accueil_personnels",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "Inconnu ou sans objet"),
                    ("aucun", "Aucun personnel"),
                    ("formés", "Personnels sensibilisés et formés"),
                    ("non-formés", "Personnels non-formés"),
                ],
                help_text="Présence et type de personnel d'accueil",
                max_length=255,
                null=True,
                verbose_name="Personnel d'accueil",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="accueil_visibilite",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (None, "Inconnu ou sans objet"),
                    (True, "Oui"),
                    (False, "Non"),
                ],
                help_text="La zone d'accueil est-elle visible depuis l'entrée ?",
                null=True,
                verbose_name="Visibilité directe de la zone d'accueil",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="ascenseur",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (None, "Inconnu ou sans objet"),
                    (True, "Oui"),
                    (False, "Non"),
                ],
                help_text="Présence d'un ascenseur ou d'un élévateur",
                null=True,
                verbose_name="Ascenseur/élévateur",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="escalier_main_courante",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (None, "Inconnu ou sans objet"),
                    (True, "Oui"),
                    (False, "Non"),
                ],
                help_text="Présence d'une main courante d'escalier",
                null=True,
                verbose_name="Main courante",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="escalier_reperage",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (None, "Inconnu ou sans objet"),
                    (True, "Oui"),
                    (False, "Non"),
                ],
                help_text="Si marches contrastées, bande d'éveil ou nez de marche contrastés, indiquez “Oui”",
                null=True,
                verbose_name="Repérage de l'escalier",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="rampe",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "Inconnu ou sans objet"),
                    ("aucune", "Aucune"),
                    ("fixe", "Fixe"),
                    ("amovible", "Amovible"),
                ],
                help_text="Présence et type de rampe",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="reperage_vitres",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (None, "Inconnu ou sans objet"),
                    (True, "Oui"),
                    (False, "Non"),
                ],
                help_text="Présence d'un repérage sur les surfaces vitrées",
                null=True,
                verbose_name="Répérage surfaces vitrées",
            ),
        ),
        migrations.AlterField(
            model_name="cheminement",
            name="ascenseur",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (None, "Inconnu ou sans objet"),
                    (True, "Oui"),
                    (False, "Non"),
                ],
                help_text="Présence d'un ascenseur ou d'un élévateur",
                null=True,
                verbose_name="Ascenseur/élévateur",
            ),
        ),
        migrations.AlterField(
            model_name="cheminement",
            name="bande_guidage",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (None, "Inconnu ou sans objet"),
                    (True, "Oui"),
                    (False, "Non"),
                ],
                help_text="Présence d'une bande de guidage",
                null=True,
                verbose_name="Bande de guidage",
            ),
        ),
        migrations.AlterField(
            model_name="cheminement",
            name="devers",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "Inconnu ou sans objet"),
                    ("aucun", "Aucun"),
                    ("léger", "Léger"),
                    ("important", "Important"),
                ],
                help_text="Inclinaison transversale du cheminement",
                max_length=15,
                null=True,
                verbose_name="Dévers",
            ),
        ),
        migrations.AlterField(
            model_name="cheminement",
            name="escalier_main_courante",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (None, "Inconnu ou sans objet"),
                    (True, "Oui"),
                    (False, "Non"),
                ],
                help_text="Présence d'une main courante d'escalier",
                null=True,
                verbose_name="Main courante",
            ),
        ),
        migrations.AlterField(
            model_name="cheminement",
            name="escalier_reperage",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (None, "Inconnu ou sans objet"),
                    (True, "Oui"),
                    (False, "Non"),
                ],
                help_text="Si marches contrastées, bande d'éveil ou nez de marche contrastés, indiquez “Oui”",
                null=True,
                verbose_name="Repérage de l'escalier",
            ),
        ),
        migrations.AlterField(
            model_name="cheminement",
            name="pente",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "Inconnu ou sans objet"),
                    ("aucune", "Aucune"),
                    ("légère", "Légère"),
                    ("importante", "Importante"),
                ],
                help_text="Présence et type de pente",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cheminement",
            name="rampe",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "Inconnu ou sans objet"),
                    ("aucune", "Aucune"),
                    ("fixe", "Fixe"),
                    ("amovible", "Amovible"),
                ],
                help_text="Présence et type de rampe",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cheminement",
            name="reperage_vitres",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (None, "Inconnu ou sans objet"),
                    (True, "Oui"),
                    (False, "Non"),
                ],
                help_text="Présence d'un repérage sur les surfaces vitrées",
                null=True,
                verbose_name="Répérage surfaces vitrées",
            ),
        ),
        migrations.AlterField(
            model_name="cheminement",
            name="type",
            field=models.CharField(
                choices=[
                    ("int", "Cheminement intérieur"),
                    ("ext", "Cheminement extérieur"),
                ],
                default="ext",
                help_text="Type de cheminement",
                max_length=255,
                verbose_name="Type",
            ),
        ),
        migrations.RunPython(migrate_cheminement_types),
    ]
