# Generated by Django 3.0.3 on 2020-02-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0050_auto_20200227_1114"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessibilite",
            name="accueil_visibilite",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                help_text="La zone d'accueil est-elle visible depuis l'entrée ?",
                null=True,
                verbose_name="Visibilité directe de la zone d'accueil",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="aide_humaine",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                help_text="Présence ou possibilité d'une aide humaine au déplacement",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="ascenseur",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                help_text="Présence d'un ascenseur ou d'un élévateur",
                null=True,
                verbose_name="Ascenseur/élévateur",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="entree_interphone",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                help_text="Présence d'un dispositif d'appel (ex. interphone)",
                null=True,
                verbose_name="Dispositif d'appel",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="entree_plain_pied",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                help_text="L'entrée est-elle de plain-pied ?",
                null=True,
                verbose_name="Plain-pied",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="entree_pmr",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                help_text="Présence d'une entrée secondaire spécifique PMR",
                null=True,
                verbose_name="Entrée spécifique PMR",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="entree_reperage",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (True, "Oui"),
                    (False, "Non"),
                    (None, "Inconnu ou sans objet"),
                ],
                help_text="Présence d'éléments de répérage de l'entrée",
                null=True,
                verbose_name="Repérage de l'entrée",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="escalier_main_courante",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (True, "Oui"),
                    (False, "Non"),
                    (None, "Inconnu ou sans objet"),
                ],
                help_text="Présence d'une main courante d'escalier",
                null=True,
                verbose_name="Main courante",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="escalier_reperage",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (True, "Oui"),
                    (False, "Non"),
                    (None, "Inconnu ou sans objet"),
                ],
                help_text="Si marches contrastées, bande d'éveil ou nez de marche contrastés, indiquez “Oui”",
                null=True,
                verbose_name="Repérage de l'escalier",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="guidage_sonore",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                help_text="Présence d'un dispositif de guidage sonore",
                null=True,
                verbose_name="Système de guidage sonore",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="reperage_vitres",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (True, "Oui"),
                    (False, "Non"),
                    (None, "Inconnu ou sans objet"),
                ],
                help_text="Présence d'un repérage sur les surfaces vitrées",
                null=True,
                verbose_name="Répérage surfaces vitrées",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="sanitaires_adaptes",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                help_text="Nombre de sanitaires adaptés dans l'établissement",
                null=True,
                verbose_name="Nombre de sanitaires adaptés",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="sanitaires_presence",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                help_text="Présence de sanitaires dans l'établissement",
                null=True,
                verbose_name="Sanitaires",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="stationnement_ext_pmr",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                help_text="Présence de stationnements PMR à proximité (200m)",
                null=True,
                verbose_name="Stationnements PMR à proximité",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="stationnement_ext_presence",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                help_text="Présence de stationnements à proximité (200m)",
                null=True,
                verbose_name="Stationnement à proximité",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="stationnement_pmr",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                help_text="Présence de stationnements PMR au sein de l'ERP",
                null=True,
                verbose_name="Stationnements PMR dans l'ERP",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="stationnement_presence",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                help_text="Présence de stationnements au sein de l'ERP",
                null=True,
                verbose_name="Stationnement dans l'ERP",
            ),
        ),
        migrations.AlterField(
            model_name="cheminement",
            name="aide_humaine",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                help_text="Présence ou possibilité d'une aide humaine au déplacement",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cheminement",
            name="ascenseur",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                help_text="Présence d'un ascenseur ou d'un élévateur",
                null=True,
                verbose_name="Ascenseur/élévateur",
            ),
        ),
        migrations.AlterField(
            model_name="cheminement",
            name="bande_guidage",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                help_text="Présence d'une bande de guidage",
                null=True,
                verbose_name="Bande de guidage",
            ),
        ),
        migrations.AlterField(
            model_name="cheminement",
            name="escalier_main_courante",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (True, "Oui"),
                    (False, "Non"),
                    (None, "Inconnu ou sans objet"),
                ],
                help_text="Présence d'une main courante d'escalier",
                null=True,
                verbose_name="Main courante",
            ),
        ),
        migrations.AlterField(
            model_name="cheminement",
            name="escalier_reperage",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (True, "Oui"),
                    (False, "Non"),
                    (None, "Inconnu ou sans objet"),
                ],
                help_text="Si marches contrastées, bande d'éveil ou nez de marche contrastés, indiquez “Oui”",
                null=True,
                verbose_name="Repérage de l'escalier",
            ),
        ),
        migrations.AlterField(
            model_name="cheminement",
            name="guidage_sonore",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                help_text="Présence d'un dispositif de guidage sonore",
                null=True,
                verbose_name="Système de guidage sonore",
            ),
        ),
        migrations.AlterField(
            model_name="cheminement",
            name="reperage_vitres",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (True, "Oui"),
                    (False, "Non"),
                    (None, "Inconnu ou sans objet"),
                ],
                help_text="Présence d'un repérage sur les surfaces vitrées",
                null=True,
                verbose_name="Répérage surfaces vitrées",
            ),
        ),
        migrations.AlterField(
            model_name="erp",
            name="published",
            field=models.BooleanField(
                default=True,
                help_text="Statut de publication de cet ERP: si la case est décochée, l'ERP ne sera pas listé publiquement.",
                verbose_name="Publié",
            ),
        ),
    ]
