# Generated by Django 3.0.3 on 2020-02-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0051_auto_20200227_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessibilite',
            name='accueil_personnels',
            field=models.CharField(blank=True, choices=[('aucun', 'Aucun personnel'), ('formés', 'Personnels sensibilisés et formés'), ('non-formés', 'Personnels non-formés'), (None, 'Inconnu ou sans objet')], help_text="Présence et type de personnel d'accueil", max_length=255, null=True, verbose_name="Personnel d'accueil"),
        ),
        migrations.AlterField(
            model_name='accessibilite',
            name='rampe',
            field=models.CharField(blank=True, choices=[('aucune', 'Aucune'), ('fixe', 'Fixe'), ('amovible', 'Amovible'), (None, 'Inconnu ou sans objet')], help_text='Présence et type de rampe', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accessibilite',
            name='sanitaires_adaptes',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Nombre de sanitaires adaptés dans l'établissement", null=True, verbose_name='Nombre de sanitaires adaptés'),
        ),
        migrations.AlterField(
            model_name='cheminement',
            name='devers',
            field=models.CharField(blank=True, choices=[('aucun', 'Aucun'), ('léger', 'Léger'), ('important', 'Important'), (None, 'Inconnu ou sans objet')], help_text='Inclinaison transversale du cheminement', max_length=15, null=True, verbose_name='Dévers'),
        ),
        migrations.AlterField(
            model_name='cheminement',
            name='pente',
            field=models.CharField(blank=True, choices=[('aucune', 'Aucune'), ('légère', 'Légère'), ('importante', 'Importante'), (None, 'Inconnu ou sans objet')], help_text='Présence et type de pente', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cheminement',
            name='rampe',
            field=models.CharField(blank=True, choices=[('aucune', 'Aucune'), ('fixe', 'Fixe'), ('amovible', 'Amovible'), (None, 'Inconnu ou sans objet')], help_text='Présence et type de rampe', max_length=20, null=True),
        ),
    ]
