# Generated by Django 3.0.3 on 2020-03-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0055_auto_20200227_1732'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activite',
            index=models.Index(fields=['slug'], name='erp_activit_slug_872ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='equipementmalentendant',
            index=models.Index(fields=['slug'], name='erp_equipem_slug_3df33d_idx'),
        ),
        migrations.AddIndex(
            model_name='erp',
            index=models.Index(fields=['slug'], name='erp_erp_slug_c17aa1_idx'),
        ),
        migrations.AddIndex(
            model_name='erp',
            index=models.Index(fields=['commune', 'activite_id'], name='erp_erp_commune_42668e_idx'),
        ),
        migrations.AddIndex(
            model_name='label',
            index=models.Index(fields=['slug'], name='erp_label_slug_54d2ad_idx'),
        ),
    ]
