# Generated by Django 3.0.3 on 2020-03-04 22:20

from django.conf import settings
from django.contrib.admin.models import ADDITION, LogEntry
from django.db import migrations, models
import django.db.models.deletion


def add_user(apps, schema_editor):
    Erp = apps.get_model("erp", "Erp")

    for erp in Erp.objects.all():
        try:
            user = LogEntry.objects.get(
                content_type__model="erp",
                action_flag=ADDITION,
                object_id=erp.pk,
            ).user
            erp.user_id = user.pk
            erp.save()
            print(f"Set user for Erp {erp}: {user.username}")
        except LogEntry.DoesNotExist:
            continue


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("erp", "0056_auto_20200303_2217"),
    ]

    operations = [
        migrations.AddField(
            model_name="erp",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(add_user),
    ]
