# Generated by Django 3.0.4 on 2020-03-12 17:59

from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0059_auto_20200312_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessibilite',
            name='accueil_cheminement_rampe',
            field=models.CharField(blank=True, choices=[('aucune', 'Aucune'), ('fixe', 'Fixe'), ('amovible', 'Amovible'), (None, 'Inconnu')], help_text='Présence et type de rampe', max_length=20, null=True, verbose_name='Rampe'),
        ),
        migrations.AlterField(
            model_name='accessibilite',
            name='entree_aide_humaine',
            field=models.BooleanField(blank=True, choices=[(True, 'Oui'), (False, 'Non'), (None, 'Inconnu')], help_text="Présence ou possibilité d'une aide humaine au déplacement", null=True, verbose_name='Aide humaine'),
        ),
        migrations.AlterField(
            model_name='accessibilite',
            name='erp',
            field=models.OneToOneField(blank=True, help_text='ERP', null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Erp', verbose_name='Établissement'),
        ),
        migrations.AlterField(
            model_name='accessibilite',
            name='labels_familles_handicap',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('auditif', 'Auditif'), ('mental', 'Mental'), ('moteur', 'Moteur'), ('visuel', 'Visuel')], max_length=255), blank=True, default=list, null=True, size=None, verbose_name='Famille(s) de handicap concernées(s)'),
        ),
    ]
