# Generated by Django 3.0.4 on 2020-03-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0063_auto_20200313_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessibilite',
            old_name='entree_reperage_vitres',
            new_name='entree_vitree_vitrophanie',
        ),
    ]
