# Generated by Django 3.0.5 on 2020-04-23 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0068_auto_20200423_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessibilite',
            old_name='presence_exterieur',
            new_name='cheminement_ext_presence',
        ),
    ]
