# Generated by Django 3.0.5 on 2020-05-04 20:30

import autoslug.fields
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0073_auto_20200501_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom', max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, help_text="Identifiant d'URL (slug)", populate_from=['departement', 'nom'], unique=True)),
                ('departement', models.CharField(help_text='Codé sur deux ou trois caractères.', max_length=3, verbose_name='Département')),
                ('superficie', models.PositiveIntegerField(blank=True, help_text='Exprimée en mètres carrés (m²)', null=True, verbose_name='Superficie')),
                ('geom', django.contrib.gis.db.models.fields.PointField(help_text='Coordonnées géographique du centre de la commune', srid=4326, verbose_name='Localisation')),
                ('code_postaux', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=list, help_text='Liste des codes postaux de cette commune', size=None, verbose_name='Codes postaux')),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
    ]
