# Generated by Django 3.0.5 on 2020-05-04 20:44

import autoslug.fields
from django.db import migrations
import erp.models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0074_commune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, help_text="Identifiant d'URL (slug)", populate_from=erp.models.generate_commune_slug, unique=True),
        ),
    ]
