# Generated by Django 3.0.5 on 2020-05-04 20:47

import autoslug.fields
from django.db import migrations
import erp.models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0075_auto_20200504_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, help_text="Identifiant d'URL (slug)", populate_from=erp.models.generate_commune_slug, unique_with=['departement', 'nom']),
        ),
    ]
