# Generated by Django 3.0.6 on 2020-05-25 12:47

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion

equipements_data = {}


def prepare_equipements_data(apps, schema_editor):
    # Valeurs existantes en base
    # ['Aucun', 'Autres', 'BIM', 'LSF', 'Service de communication à distance']
    Accessibilite = apps.get_model("erp", "Accessibilite")
    for a in Accessibilite.objects.all():
        existing = [
            eq["nom"] for eq in a.accueil_equipements_malentendants.values("nom")
        ]
        to_add = []
        if "Aucun" in existing:
            to_add.append("aucun")
        if "Autres" in existing:
            to_add.append("autres")
        if "BIM" in existing:
            to_add.append("bim")
        if "LSF" in existing:
            to_add.append("lsf")
        if "Service de communication à distance" in existing:
            to_add.append("scd")
        equipements_data[a.pk] = to_add


def migrate_equipements_malentendant(apps, schema_editor):
    Accessibilite = apps.get_model("erp", "Accessibilite")
    for a in Accessibilite.objects.all():
        equipements = equipements_data.get(a.id)
        if equipements is not None:
            a.accueil_equipements_malentendants = equipements
            label = f"{a} (#{a.pk}) with {a.accueil_equipements_malentendants}"
            a.save()
            print(f"PASS: migrated {label}")
        else:
            print(f"WARN: no existing data for {label}")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("erp", "0076_auto_20200512_1443"),
    ]

    operations = [
        migrations.RunPython(prepare_equipements_data),
        migrations.AlterField(
            model_name="accessibilite",
            name="accueil_cheminement_ascenseur",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Ascenseur/élévateur",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="accueil_cheminement_main_courante",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (True, "Oui"),
                    (False, "Non"),
                    (None, "Inconnu ou sans objet"),
                ],
                null=True,
                verbose_name="Main courante",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="accueil_cheminement_nombre_marches",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Nombre de marches"
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="accueil_cheminement_plain_pied",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (True, "Oui"),
                    (False, "Non"),
                    (None, "Inconnu ou sans objet"),
                ],
                null=True,
                verbose_name="Cheminement de plain pied",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="accueil_cheminement_rampe",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aucune", "Aucune"),
                    ("fixe", "Fixe"),
                    ("amovible", "Amovible"),
                    (None, "Inconnu"),
                ],
                max_length=20,
                null=True,
                verbose_name="Rampe",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="accueil_cheminement_reperage_marches",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Repérage des marches ou de l’escalier",
            ),
        ),
        migrations.RemoveField(
            model_name="accessibilite", name="accueil_equipements_malentendants",
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_equipements_malentendants",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("aucun", "Aucun"),
                        ("autres", "Autres"),
                        ("bim", "BIM"),
                        ("lsf", "LSF"),
                        ("scd", "Service de communication à distance"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="Équipement(s) sourd/malentendant",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="accueil_personnels",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aucun", "Aucun personnel"),
                    ("formés", "Personnels sensibilisés et formés"),
                    ("non-formés", "Personnels non-formés"),
                    (None, "Inconnu"),
                ],
                max_length=255,
                null=True,
                verbose_name="Personnel d'accueil",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="accueil_prestations",
            field=models.TextField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Prestations d'accueil adapté supplémentaires",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="accueil_retrecissement",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Rétrécissement du cheminement",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="accueil_visibilite",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Visibilité directe de la zone d'accueil depuis l'entrée",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="cheminement_ext_ascenseur",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Ascenseur/élévateur",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="cheminement_ext_bande_guidage",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Bande de guidage",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="cheminement_ext_devers",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aucun", "Aucun"),
                    ("léger", "Léger"),
                    ("important", "Important"),
                    (None, "Inconnu ou sans objet"),
                ],
                max_length=15,
                null=True,
                verbose_name="Dévers",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="cheminement_ext_main_courante",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (True, "Oui"),
                    (False, "Non"),
                    (None, "Inconnu ou sans objet"),
                ],
                null=True,
                verbose_name="Main courante",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="cheminement_ext_nombre_marches",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Nombre de marches"
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="cheminement_ext_pente",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aucune", "Aucune"),
                    ("légère", "Légère"),
                    ("importante", "Importante"),
                    (None, "Inconnu ou sans objet"),
                ],
                max_length=15,
                null=True,
                verbose_name="Pente",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="cheminement_ext_plain_pied",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Cheminement de plain-pied",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="cheminement_ext_presence",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (True, "Oui"),
                    (False, "Non"),
                    (None, "Inconnu ou sans objet"),
                ],
                null=True,
                verbose_name="Espace extérieur",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="cheminement_ext_rampe",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aucune", "Aucune"),
                    ("fixe", "Fixe"),
                    ("amovible", "Amovible"),
                    (None, "Inconnu"),
                ],
                max_length=20,
                null=True,
                verbose_name="Rampe",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="cheminement_ext_reperage_marches",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Repérage des marches ou de l’escalier",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="cheminement_ext_retrecissement",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Rétrécissement du cheminement",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="cheminement_ext_terrain_accidente",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Terrain meuble ou accidenté",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="commentaire",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Commentaire libre"
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="entree_aide_humaine",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Aide humaine",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="entree_ascenseur",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Ascenseur/élévateur",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="entree_balise_sonore",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Présence d'une balise sonore",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="entree_dispositif_appel",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Dispositif d'appel",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="entree_largeur_mini",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Largeur minimale"
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="entree_marches",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Marches d'escalier"
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="entree_marches_main_courante",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (True, "Oui"),
                    (False, "Non"),
                    (None, "Inconnu ou sans objet"),
                ],
                null=True,
                verbose_name="Main courante",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="entree_marches_rampe",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aucune", "Aucune"),
                    ("fixe", "Fixe"),
                    ("amovible", "Amovible"),
                    (None, "Inconnu"),
                ],
                max_length=20,
                null=True,
                verbose_name="Rampe",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="entree_marches_reperage",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (True, "Oui"),
                    (False, "Non"),
                    (None, "Inconnu ou sans objet"),
                ],
                null=True,
                verbose_name="Repérage de l'escalier",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="entree_plain_pied",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Entrée de plain-pied",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="entree_pmr",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Entrée spécifique PMR",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="entree_pmr_informations",
            field=models.TextField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Infos entrée spécifique PMR",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="entree_reperage",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (True, "Oui"),
                    (False, "Non"),
                    (None, "Inconnu ou sans objet"),
                ],
                null=True,
                verbose_name="Entrée facilement repérable",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="entree_vitree",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Entrée vitrée",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="entree_vitree_vitrophanie",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (True, "Oui"),
                    (False, "Non"),
                    (None, "Inconnu ou sans objet"),
                ],
                null=True,
                verbose_name="Vitrophanie",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="labels",
            field=models.ManyToManyField(
                blank=True, to="erp.Label", verbose_name="Marques ou labels"
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="labels_autre",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Autre label"
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="labels_familles_handicap",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("auditif", "Auditif"),
                        ("mental", "Mental"),
                        ("moteur", "Moteur"),
                        ("visuel", "Visuel"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="Famille(s) de handicap concernées(s)",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="sanitaires_adaptes",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Nombre de sanitaires adaptés"
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="sanitaires_presence",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Sanitaires",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="stationnement_ext_pmr",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Stationnements PMR à proximité de l'ERP",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="stationnement_ext_presence",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Stationnement à proximité de l'ERP",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="stationnement_pmr",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Stationnements PMR dans l'ERP",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="stationnement_presence",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Stationnement dans l'ERP",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="transport_information",
            field=models.TextField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Informations transports",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="transport_station_presence",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Desserte par transports en commun",
            ),
        ),
        migrations.AlterField(
            model_name="erp",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.RunPython(migrate_equipements_malentendant),
    ]
