# Generated by Django 3.0.6 on 2020-05-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0077_auto_20200525_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EquipementMalentendant',
        ),
    ]
