# Generated by Django 3.0.7 on 2020-07-07 15:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0081_auto_20200629_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='codes_naf',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=5), blank=True, default=list, help_text='Liste des codes NAF associés à cette activité', null=True, size=None, verbose_name='Codes NAF'),
        ),
    ]
