# Generated by Django 3.0.7 on 2020-07-20 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("erp", "0083_auto_20200715_1252"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.SmallIntegerField(
                        choices=[(-1, "-1"), (1, "+1")],
                        default=1,
                        verbose_name="Valeur",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Commentaire",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "erp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.Erp",
                        verbose_name="Établissemet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(fields=["value"], name="erp_vote_value_fa7ddf_idx"),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["erp", "value"], name="erp_vote_erp_id_1853cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["erp", "user", "value"], name="erp_vote_erp_id_108b22_idx"
            ),
        ),
    ]
