# Generated by Django 3.0.7 on 2020-07-21 15:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("erp", "0084_auto_20200720_1644"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("erp", "user")},
        ),
    ]
