# Generated by Django 3.0.7 on 2020-07-22 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0085_auto_20200721_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='icon',
            field=models.CharField(blank=True, help_text='Chemin de l\'icône <a href="http://www.sjjb.co.uk/mapicons/contactsheet" target="_blank">SSJB</a> (ex. <code>sport_motorracing</code>)', max_length=120, null=True, verbose_name='Icône'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='erp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Erp', verbose_name='Établissement'),
        ),
    ]
