# Generated by Django 3.0.7 on 2020-08-24 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0087_auto_20200728_1511"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusCheck",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(verbose_name="Toujours en activité")),
                (
                    "last_checked",
                    models.DateTimeField(verbose_name="Dernière vérification"),
                ),
                (
                    "erp",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.Erp",
                        verbose_name="Établissement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vérification de statut",
                "verbose_name_plural": "Vérifications de statut",
            },
        ),
    ]
