# Generated by Django 3.0.7 on 2020-08-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0088_statuscheck"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuscheck",
            name="last_checked",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Dernière vérification"
            ),
        ),
    ]
