# Generated by Django 3.0.7 on 2020-09-08 13:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0089_auto_20200824_1643"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessibilite",
            name="accueil_equipements_malentendants",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("aucun", "Aucun"),
                        ("autres", "Autres"),
                        ("bim", "Boucle à induction magnétique"),
                        ("lsf", "Langue des signes française"),
                        ("scd", "Service de communication à distance"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="Équipement(s) sourd/malentendant",
            ),
        ),
    ]
