# Generated by Django 3.1.1 on 2020-09-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0090_auto_20200908_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessibilite',
            name='conformite',
            field=models.BooleanField(blank=True, choices=[(True, 'Oui'), (False, 'Non'), (None, 'Inconnu')], null=True, verbose_name='Conformité'),
        ),
    ]
