# Generated by Django 3.1.1 on 2020-09-16 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0091_auto_20200914_1720'),
        ('erp', '0091_auto_20200914_1638'),
    ]

    operations = [
    ]
