# Generated by Django 3.1.1 on 2020-10-27 08:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0095_auto_20201015_1743"),
    ]

    operations = [
        migrations.RemoveField(model_name="accessibilite", name="labels",),
        migrations.AddField(
            model_name="accessibilite",
            name="labels",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("autre", "Autre"),
                        ("dpt", "Destination pour Tous"),
                        ("th", "Tourisme & Handicap"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="Marques ou labels",
            ),
        ),
        migrations.AlterField(
            model_name="erp",
            name="source",
            field=models.CharField(
                choices=[
                    ("admin", "Back-office"),
                    ("api", "API"),
                    ("entreprise_api", "API Entreprise (publique)"),
                    ("cconforme", "cconforme"),
                    ("public", "Saisie manuelle publique"),
                    ("public_erp", "API des établissements publics"),
                    ("sirene", "API Sirene INSEE"),
                    ("tourisme-handicap", "Tourisme & Handicap"),
                ],
                default="public",
                help_text="Nom de la source de données dont est issu cet ERP",
                max_length=100,
                null=True,
                verbose_name="Source",
            ),
        ),
        migrations.DeleteModel(name="Label",),
    ]
