# Generated by Django 3.1.1 on 2020-10-28 09:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0096_auto_20201027_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessibilite',
            name='labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('autre', 'Autre'), ('dpt', 'Destination pour Tous'), ('mobalib', 'Mobalib'), ('th', 'Tourisme & Handicap')], max_length=255), blank=True, default=list, null=True, size=None, verbose_name='Marques ou labels'),
        ),
    ]
