# Generated by Django 3.1.3 on 2020-12-02 08:33

import django.contrib.postgres.fields
from django.db import migrations, models


def migrate_equipement_choices(apps, schema_editor):
    Accessibilite = apps.get_model("erp", "Accessibilite")
    to_be_updated = Accessibilite.objects.filter(
        accueil_equipements_malentendants__contains=["aucun"]
    )
    for accessibilite in to_be_updated:
        accessibilite.accueil_equipements_malentendants = [
            x for x in accessibilite.accueil_equipements_malentendants if x != "aucun"
        ]
        accessibilite.save()


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0100_statuscheck_non_diffusable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessibilite",
            name="accueil_equipements_malentendants",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("autres", "Autres"),
                        ("bim", "Boucle à induction magnétique"),
                        ("lsf", "Langue des signes française"),
                        ("scd", "Service de communication à distance"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="Équipement(s) sourd/malentendant",
            ),
        ),
        migrations.RunPython(migrate_equipement_choices),
    ]
