# Generated by Django 3.1.5 on 2021-02-01 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0102_auto_20201215_1647'),
    ]

    operations = [
    ]
