# Generated by Django 3.1.5 on 2021-02-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0103_auto_20210129_1101'),
    ]

    operations = [
        migrations.RunSQL('update erp_accessibilite '
                          'set accueil_equipements_malentendants_presence = true '
                          'where accueil_equipements_malentendants <> \'{}\'',
                          elidable=True)
    ]
