# Generated by Django 3.1.5 on 2021-02-03 18:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0104_equipement_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessibilite',
            name='accueil_equipements_malentendants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('bim', 'Boucle à induction magnétique'), ('lsf', 'Langue des signes française'), ('lpc', 'Langue Française Parlée Complétée (LFPC)'), ('scd', 'Service de communication à distance'), ('autres', 'Autres')], max_length=255), blank=True, default=list, null=True, size=None, verbose_name='Équipement(s) sourd/malentendant'),
        ),
        migrations.AlterField(
            model_name='accessibilite',
            name='accueil_equipements_malentendants_presence',
            field=models.BooleanField(blank=True, choices=[(True, 'Oui'), (False, 'Non'), (None, 'Inconnu')], null=True, verbose_name="Présence d'équipement(s) sourds/malentendants"),
        ),
    ]
