# Generated by Django 3.1.5 on 2021-02-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0105_auto_20210203_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erp',
            name='source',
            field=models.CharField(choices=[('admin', 'Back-office'), ('api', 'API'), ('entreprise_api', 'API Entreprise (publique)'), ('cconforme', 'cconforme'), ('opendatasoft', 'API OpenDataSoft'), ('pagesjaunes', 'PagesJaunes.fr'), ('public', 'Saisie manuelle publique'), ('public_erp', 'API des établissements publics'), ('sirene', 'API Sirene INSEE'), ('tourisme-handicap', 'Tourisme & Handicap')], default='public', help_text='Nom de la source de données dont est issu cet ERP', max_length=100, null=True, verbose_name='Source'),
        ),
    ]
