# Generated by Django 3.1.5 on 2021-02-17 13:46

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0106_invert_data_on_cheminement_ext_terrain_accidente"),
    ]

    operations = [
        migrations.AddField(
            model_name="erp",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name="erp",
            index=django.contrib.postgres.indexes.GinIndex(fields=["metadata"], name="gin_metadata"),
        ),
    ]
