# Generated by Django 3.1.5 on 2021-02-17 16:48

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0107_auto_20210217_1446"),
    ]

    operations = [
        migrations.AlterField(
            model_name="erp",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="",
                editable=False,
                help_text="Identifiant d'URL (slug)",
                max_length=255,
                populate_from="nom",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="erp",
            name="source",
            field=models.CharField(
                choices=[
                    ("admin", "Back-office"),
                    ("api", "API"),
                    ("entreprise_api", "API Entreprise (publique)"),
                    ("cconforme", "cconforme"),
                    ("opendatasoft", "API OpenDataSoft"),
                    ("public", "Saisie manuelle publique"),
                    ("public_erp", "API des établissements publics"),
                    ("sirene", "API Sirene INSEE"),
                    ("tourisme-handicap", "Tourisme & Handicap"),
                    ("centres-vaccination", "Centres de vaccination"),
                ],
                default="public",
                help_text="Nom de la source de données dont est issu cet ERP",
                max_length=100,
                null=True,
                verbose_name="Source",
            ),
        ),
    ]
