# Generated by Django 3.1.8 on 2021-04-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0111_auto_20210414_1247"),
    ]

    operations = [
        migrations.AddField(
            model_name="erp",
            name="contact_url",
            field=models.URLField(
                blank=True,
                help_text="Lien hypertexte permettant de contacter l'établissement (formulaire, chatbot, etc.)",
                max_length=255,
                null=True,
                verbose_name="Lien vers outil de contact",
            ),
        ),
    ]
