# Generated by Django 3.2 on 2021-04-15 12:59

from django.db import migrations


def migrate_prestations_to_commentaire(apps, schema_editor):
    Accessibilite = apps.get_model("erp", "Accessibilite")
    for a in Accessibilite.objects.all():
        accueil_prestations = a.accueil_prestations or ""
        commentaire = a.commentaire or ""
        a.commentaire = (accueil_prestations + "\n\n" + commentaire).strip() or None
        a.save()


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0112_erp_contact_url"),
    ]

    operations = [
        migrations.RunPython(migrate_prestations_to_commentaire),
        migrations.RemoveField(
            model_name="accessibilite",
            name="accueil_prestations",
        ),
    ]
