# Generated by Django 3.2 on 2021-04-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0116_auto_20210419_1309"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessibilite",
            name="entree_porte_manoeuvre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("battante", "Porte battante"),
                    ("coulissante", "Porte coulissante"),
                    ("tourniquet", "Tourniquet"),
                    ("tambour", "Porte tambour"),
                    (None, "Inconnu"),
                ],
                max_length=255,
                null=True,
                verbose_name="Manœuvre de la porte",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="entree_porte_presence",
            field=models.BooleanField(
                null=True,
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                verbose_name="Y a-t-il une porte ?",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="entree_porte_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manuelle", "Manuelle"),
                    ("automatique", "Automatique"),
                    (None, "Inconnu ou sans objet"),
                ],
                max_length=255,
                null=True,
                verbose_name="Type de porte",
            ),
        ),
    ]
