# Generated by Django 3.2 on 2021-04-27 10:59

from django.db import migrations, models


def migrate_previous_data(apps, schema_editor):
    Accessibilite = apps.get_model("erp", "Accessibilite")
    for a in Accessibilite.objects.all():
        if a.cheminement_ext_pente_degre_difficulte == "aucune":
            a.cheminement_ext_pente_degre_difficulte = "légère"
            a.save()


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0117_auto_20210426_1112"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessibilite",
            name="cheminement_ext_pente_degre_difficulte",
            field=models.CharField(
                blank=True,
                choices=[
                    ("légère", "Légère"),
                    ("importante", "Importante"),
                    (None, "Inconnu"),
                ],
                max_length=15,
                null=True,
                verbose_name="Difficulté de la pente",
            ),
        ),
        migrations.RunPython(migrate_previous_data),
    ]
