# Generated by Django 3.2 on 2021-04-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0118_alter_accessibilite_cheminement_ext_pente_degre_difficulte"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessibilite",
            name="cheminement_ext_pente_longueur",
            field=models.CharField(
                blank=True,
                choices=[
                    ("courte", "< 0,5 mètres"),
                    ("moyenne", "entre 0,5 et 2 mètres"),
                    ("longue", "> 2 mètres"),
                    (None, "Inconnu"),
                ],
                max_length=15,
                null=True,
                verbose_name="Longueur de la pente",
            ),
        ),
    ]
