# Generated by Django 3.2 on 2021-05-13 15:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0120_alter_accessibilite_entree_dispositif_appel_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="erp",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
