# Generated by Django 3.2 on 2021-05-13 15:20
import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    Erp = apps.get_model("erp", "Erp")
    for row in Erp.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0121_erp_uuid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
