# Generated by Django 3.2 on 2021-05-13 15:20
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0122_auto_20210513_1720"),
    ]

    operations = [
        migrations.AlterField(
            model_name="erp",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
