# Generated by Django 3.2 on 2021-05-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0123_auto_20210513_1720"),
    ]

    operations = [
        migrations.AddField(
            model_name="erp",
            name="private_contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Email permettant de notifier le fournisseur en cas de modifications par un tier",
                max_length=255,
                null=True,
                verbose_name="Courriel privé",
            ),
        ),
        migrations.AlterField(
            model_name="erp",
            name="source",
            field=models.CharField(
                choices=[
                    ("admin", "Back-office"),
                    ("api", "API"),
                    ("entreprise_api", "API Entreprise (publique)"),
                    ("cconforme", "cconforme"),
                    ("opendatasoft", "API OpenDataSoft"),
                    ("public", "Saisie manuelle publique"),
                    ("public_erp", "API des établissements publics"),
                    ("sirene", "API Sirene INSEE"),
                    ("tourisme-handicap", "Tourisme & Handicap"),
                    ("centres-vaccination", "Centres de vaccination"),
                    ("gendarmerie", "Gendarmerie"),
                ],
                default="public",
                help_text="Nom de la source de données dont est issu cet ERP",
                max_length=100,
                null=True,
                verbose_name="Source",
            ),
        ),
    ]
