# Generated by Django 3.2 on 2021-06-03 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0124_alter_accessibilite_entree_dispositif_appel_type'),
        ('erp', '0124_auto_20210525_1231'),
    ]

    operations = [
    ]
