# Generated by Django 3.2.1 on 2021-06-12 08:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0126_auto_20210604_1611"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessibilite",
            name="labels_familles_handicap",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("auditif", "Handicap auditif"),
                        ("mental", "Handicap mental"),
                        ("moteur", "Handicap moteur"),
                        ("visuel", "Handicap visuel"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="Famille(s) de handicap concernées(s)",
            ),
        ),
    ]
