# Generated by Django 3.2.1 on 2021-06-15 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0127_alter_accessibilite_labels_familles_handicap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusCheck',
        ),
    ]
