# Generated by Django 3.2.4 on 2021-06-26 09:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0128_delete_statuscheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='contour',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(help_text='Contour de la commune', null=True, srid=4326, verbose_name='Contour'),
        ),
    ]
