# Generated by Django 3.2.5 on 2022-03-28 10:25

from django.db import migrations


def migrate_sanitaires_adaptes(apps, schema_editor):
    Accessibilite = apps.get_model("erp", "Accessibilite")
    for a in Accessibilite.objects.all():
        if a.sanitaires_adaptes is None:
            value = None
        else:
            value = bool(a.sanitaires_adaptes)
        a.sanitaires_adaptes_booltemp = value
        a.save()


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0132_auto_20220328_1224"),
    ]

    operations = [
        migrations.RunPython(migrate_sanitaires_adaptes),
    ]
