# Generated by Django 3.2.5 on 2022-03-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0133_auto_20220328_1225"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accessibilite",
            name="sanitaires_adaptes",
        ),
        migrations.RenameField(
            model_name="accessibilite",
            old_name="sanitaires_adaptes_booltemp",
            new_name="sanitaires_adaptes",
        ),
    ]
