# Generated by Django 3.2.13 on 2022-05-16 13:02

from django.db import migrations
from django.db.migrations import RunPython
from django.db.models import Q


def update_erp_accueil_equipements_malentendants(apps, schema_editor):
    Erp = apps.get_model("erp", "Erp")
    for erp in Erp.objects.filter(accessibilite__isnull=False).filter(
        Q(accessibilite__accueil_equipements_malentendants_presence=False)
        | Q(accessibilite__accueil_equipements_malentendants_presence__isnull=True),
        accessibilite__accueil_equipements_malentendants__len__gt=0,
    ):
        erp.accessibilite.accueil_equipements_malentendants = []
        erp.accessibilite.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            "erp",
            "0135_rename_cheminement_ext_terrain_accidente_accessibilite_cheminement_ext_terrain_stable",
        ),
    ]

    operations = [RunPython(update_erp_accueil_equipements_malentendants)]
