# Generated by Django 3.2.13 on 2022-08-30 09:57

from django.db import migrations
from django.db.migrations import RunPython

from erp.models import get_last_position


def update_activite_position(apps, schema_editor):
    Activite = apps.get_model("erp", "Activite")
    for act in Activite.objects.all().order_by("nom"):
        act.position = get_last_position()
        act.save()


def add_activite_autre(apps, schema_editor):
    Activite = apps.get_model("erp", "Activite")
    Activite.objects.create(nom="Autre", vector_icon="building", position=get_last_position())


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0138_auto_20220803_0845"),
    ]

    operations = [
        RunPython(update_activite_position),
        RunPython(add_activite_autre),
    ]
