# Generated by Django 3.2.13 on 2022-09-01 12:26

from django.db import migrations
from django.db.migrations import RunPython

from erp.models import Activite as Activite_class


def reorder(apps, schema_editor):
    Activite = apps.get_model("erp", "Activite")

    for act in Activite.objects.all():
        if act.nom[0].islower():
            act.nom = act.nom.capitalize()
            act.save()
    Activite_class.reorder()


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0139_auto_20220830_1157"),
    ]

    operations = [
        RunPython(reorder),
    ]
