# Generated by Django 3.2.16 on 2022-12-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0143_erp_import_email"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="erp",
            index=models.Index(fields=["nom"], name="erp_erp_nom_58d353_idx"),
        ),
    ]
