# Generated by Django 3.2.16 on 2023-01-02 09:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0145_auto_20221213_1111"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessibilite",
            name="accueil_audiodescription",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        (
                            "avec_équipement_permanent",
                            "avec équipement permanent, casques et boîtiers disponibles à l’accueil",
                        ),
                        (
                            "avec_app",
                            "avec équipement permanent nécessitant le téléchargement d'une application sur smartphone",
                        ),
                        ("avec_équipement_occasionnel", "avec équipement occasionnel selon la programmation"),
                        (
                            "sans_équipement",
                            "sans équipement, audiodescription audible par toute la salle (selon la programmation)",
                        ),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="Équipement(s) audiodescription",
            ),
        ),
    ]
