# Generated by Django 3.2.16 on 2023-01-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0146_alter_accessibilite_accueil_audiodescription"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="erp",
            index=models.Index(fields=["published", "geom"], name="erp_erp_publish_c6bbad_idx"),
        ),
    ]
