# Generated by Django 3.2.17 on 2023-02-16 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0149_activity_suggestions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitysuggestion",
            name="mapped_activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="erp.activite",
                verbose_name="Activité attribuée",
            ),
        ),
        migrations.AlterField(
            model_name="activitysuggestion",
            name="name",
            field=models.CharField(help_text="Nom suggéré pour l'activité", max_length=255),
        ),
    ]
