# Generated by Django 3.2.18 on 2023-02-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0150_activity_suggestions_name_non_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessibilite",
            name="completion_rate",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
