# Generated by Django 3.2.18 on 2023-03-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0152_geolocation_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessibilite",
            name="completion_rate",
            field=models.PositiveIntegerField(default=0, verbose_name="Taux de complétion"),
        ),
        migrations.AlterField(
            model_name="activite",
            name="vector_icon",
            field=models.CharField(
                blank=True,
                default="building",
                help_text='Nom de l\'icône dans<a href="/mapicons" target="_blank">le catalogue</a>.',
                max_length=120,
                null=True,
                verbose_name="Icône vectorielle",
            ),
        ),
        migrations.AlterField(
            model_name="erp",
            name="source",
            field=models.CharField(
                choices=[
                    ("acceslibre", "Base de données Acceslibre"),
                    ("acceo", "Acceo"),
                    ("admin", "Back-office"),
                    ("api", "API"),
                    ("entreprise_api", "API Entreprise (publique)"),
                    ("cconforme", "cconforme"),
                    ("gendarmerie", "Gendarmerie"),
                    ("lorient", "Lorient"),
                    ("nestenn", "Nestenn"),
                    ("opendatasoft", "API OpenDataSoft"),
                    ("public", "Saisie manuelle publique"),
                    ("public_erp", "API des établissements publics"),
                    ("sap", "Sortir À Paris"),
                    ("service_public", "Service Public"),
                    ("sirene", "API Sirene INSEE"),
                    ("tourisme-handicap", "Tourisme & Handicap"),
                    ("typeform", "Questionnaires Typeform"),
                    ("typeform_musee", "Questionnaires Typeform Musée"),
                    ("centres-vaccination", "Centres de vaccination"),
                    ("dell", "Dell"),
                ],
                default="public",
                help_text="Nom de la source de données dont est issu cet ERP",
                max_length=100,
                null=True,
                verbose_name="Source",
            ),
        ),
    ]
