# Generated by Django 4.2 on 2023-04-17 14:32

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0154_activity_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_chambre_accompagnement",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Accompagnement personnalisé pour présenter la chambre",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_chambre_douche_barre_appui",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Barre d'appui dans la douche",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_chambre_douche_plain_pied",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Douche plain pied",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_chambre_douche_siege",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Siège de douche",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_chambre_equipement_alerte",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Equipement d'alerte dans la chambre",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_chambre_nombre_accessibles",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Nombre de chambres accessibles"
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_chambre_numero_visible",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Numéro de chambre visible et en relief",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_chambre_sanitaires_barre_appui",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Barre d'appui dans les sanitaires",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_chambre_sanitaires_espace_usage",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Espace d'usage dans les sanitaires",
            ),
        ),
        migrations.AlterField(
            model_name="activite",
            name="nom",
            field=models.CharField(
                help_text="Nom de l'activité",
                max_length=255,
                unique=True,
                verbose_name="Nom",
            ),
        ),
        migrations.AlterField(
            model_name="activite",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="",
                editable=False,
                help_text="Identifiant d'URL (slug)",
                populate_from="nom",
                unique=True,
                verbose_name="Identifiant d'URL (slug)",
            ),
        ),
        migrations.AlterField(
            model_name="activitiesgroup",
            name="name",
            field=models.CharField(
                help_text="Nom du groupe d'activités",
                max_length=255,
                verbose_name="Nom",
            ),
        ),
        migrations.AlterField(
            model_name="erp",
            name="code_postal",
            field=models.CharField(help_text="Code postal", max_length=5, verbose_name="Code postal"),
        ),
        migrations.AlterField(
            model_name="erp",
            name="commune",
            field=models.CharField(help_text="Nom de la commune", max_length=255, verbose_name="Commune"),
        ),
        migrations.AlterField(
            model_name="erp",
            name="lieu_dit",
            field=models.CharField(
                blank=True,
                help_text="Lieu dit",
                max_length=255,
                null=True,
                verbose_name="Lieu dit",
            ),
        ),
        migrations.AlterField(
            model_name="erp",
            name="nom",
            field=models.CharField(
                help_text="Nom de l'établissement ou de l'enseigne",
                max_length=255,
                verbose_name="Nom",
            ),
        ),
        migrations.AlterField(
            model_name="erp",
            name="site_internet",
            field=models.URLField(
                blank=True,
                help_text="Adresse du site internet de l'ERP",
                max_length=255,
                null=True,
                verbose_name="Site internet",
            ),
        ),
        migrations.AlterField(
            model_name="erp",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="",
                editable=False,
                help_text="Identifiant d'URL (slug)",
                max_length=255,
                populate_from="nom",
                unique=True,
                verbose_name="Identifiant d'URL (slug)",
            ),
        ),
        migrations.AlterField(
            model_name="erp",
            name="voie",
            field=models.CharField(
                blank=True,
                help_text="Voie",
                max_length=255,
                null=True,
                verbose_name="Voie",
            ),
        ),
    ]
