# Generated by Django 4.2 on 2023-05-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0155_accessibility_hotels"),
    ]

    operations = [
        migrations.AddField(
            model_name="activite",
            name="nom_en",
            field=models.CharField(
                help_text="Nom de l'activité",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Nom",
            ),
        ),
        migrations.AddField(
            model_name="activite",
            name="nom_fr",
            field=models.CharField(
                help_text="Nom de l'activité",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Nom",
            ),
        ),
    ]
