# Generated by Django 4.2.3 on 2023-11-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0159_ban_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="erp",
            name="check_closed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Dernière vérification de clôture"),
        ),
    ]
