# Generated by Django 4.2.3 on 2024-03-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0160_add_check_closed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="erp",
            name="permanently_closed",
            field=models.BooleanField(
                default=False,
                help_text="Statut de fermeture de cet ERP: si la case est cochée, l'ERP est définitivement clôt et ne peut pas être inséré à nouveau.",
                verbose_name="Définitivement clôt",
            ),
        ),
    ]
