# Generated by Django 4.2.3 on 2024-03-19 14:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0161_permanently_closed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessibilite",
            name="labels",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("autre", "Autre"),
                        ("dpt", "Destination pour Tous"),
                        ("mobalib", "Mobalib"),
                        ("th", "Tourisme & Handicap"),
                        ("handiplage", "Handiplage"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="Marques ou labels",
            ),
        ),
        migrations.AlterField(
            model_name="activite",
            name="naf_ape_code",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=10),
                blank=True,
                default=list,
                help_text="Liste des codes NAF/APE liés à cette activité",
                null=True,
                size=None,
                verbose_name="Code NAF/APE",
            ),
        ),
        migrations.AlterField(
            model_name="erp",
            name="source",
            field=models.CharField(
                choices=[
                    ("acceslibre", "Base de données Acceslibre"),
                    ("acceo", "Acceo"),
                    ("admin", "Back-office"),
                    ("api", "API"),
                    ("entreprise_api", "API Entreprise (publique)"),
                    ("cconforme", "cconforme"),
                    ("gendarmerie", "Gendarmerie"),
                    ("lorient", "Lorient"),
                    ("nestenn", "Nestenn"),
                    ("opendatasoft", "API OpenDataSoft"),
                    ("public", "Saisie manuelle publique"),
                    ("public_erp", "API des établissements publics"),
                    ("sap", "Sortir À Paris"),
                    ("service_public", "Service Public"),
                    ("sirene", "API Sirene INSEE"),
                    ("tourisme-handicap", "Tourisme & Handicap"),
                    ("typeform", "Questionnaires Typeform"),
                    ("typeform_musee", "Questionnaires Typeform Musée"),
                    ("centres-vaccination", "Centres de vaccination"),
                    ("dell", "Dell"),
                    ("outscraper", "Outscraper"),
                    ("scrapfly", "Scrapfly"),
                    ("tally", "Tally"),
                    ("laposte", "La Poste"),
                ],
                default="public",
                help_text="Nom de la source de données dont est issu cet ERP",
                max_length=100,
                null=True,
                verbose_name="Source",
            ),
        ),
    ]
