# Generated by Django 4.2.3 on 2024-03-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0162_alter_accessibilite_labels_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="erp",
            name="checked_up_to_date_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Dernière vérification des informations",
            ),
        ),
    ]
