# Generated by Django 4.2.3 on 2024-03-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0162_alter_accessibilite_labels_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="erp",
            name="asp_id",
            field=models.CharField(
                blank=True,
                help_text="Identifiant de l'ERP dans la base Service Public",
                max_length=255,
                null=True,
                verbose_name="ASP ID",
            ),
        ),
    ]
