# Generated by Django 4.2.3 on 2024-03-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0163_asp_id_can_be_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="erp",
            name="checked_up_to_date_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Dernière vérification des informations",
            ),
        ),
    ]
