# Generated by Django 4.2.11 on 2024-05-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0165_access_constraints"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="accessibilite",
            name="erp_accessibilite_chambre_consistency",
        ),
        migrations.AddConstraint(
            model_name="accessibilite",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("accueil_chambre_nombre_accessibles", 0),
                        ("accueil_chambre_nombre_accessibles__isnull", True),
                        _connector="OR",
                        _negated=True,
                    ),
                    models.Q(
                        ("accueil_chambre_douche_plain_pied__isnull", True),
                        ("accueil_chambre_douche_siege__isnull", True),
                        ("accueil_chambre_douche_barre_appui__isnull", True),
                        ("accueil_chambre_sanitaires_barre_appui__isnull", True),
                        ("accueil_chambre_sanitaires_espace_usage__isnull", True),
                        ("accueil_chambre_equipement_alerte__isnull", True),
                        ("accueil_chambre_numero_visible__isnull", True),
                        ("accueil_chambre_accompagnement__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="erp_accessibilite_chambre_consistency",
            ),
        ),
    ]
