# Generated by Django 4.2.11 on 2024-06-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0166_hotel_db_constraints"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
