# Generated by Django 4.2.11 on 2024-06-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0167_remove_vote"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="erp",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("published", True),
                    ("asp_id__isnull", False),
                    models.Q(("asp_id", ""), _negated=True),
                ),
                fields=("asp_id",),
                name="unique_asp_id_published",
            ),
        ),
    ]
