# Generated by Django 4.2.15 on 2024-09-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0168_erp_unique_asp_id_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessibilite",
            name="cheminement_ext_pente_longueur",
            field=models.CharField(
                blank=True,
                choices=[
                    ("courte", "inférieure à 0,5 mètres"),
                    ("moyenne", "entre 0,5 et 2 mètres"),
                    ("longue", "supérieure 2 mètres"),
                    (None, "Inconnu"),
                ],
                max_length=15,
                null=True,
                verbose_name="Longueur de la pente",
            ),
        ),
        migrations.AlterField(
            model_name="erp",
            name="source",
            field=models.CharField(
                choices=[
                    ("acceslibre", "Base de données Acceslibre"),
                    ("acceo", "Acceo"),
                    ("admin", "Back-office"),
                    ("api", "API"),
                    ("entreprise_api", "API Entreprise (publique)"),
                    ("cconforme", "cconforme"),
                    ("gendarmerie", "Gendarmerie"),
                    ("lorient", "Lorient"),
                    ("nestenn", "Nestenn"),
                    ("opendatasoft", "API OpenDataSoft"),
                    ("public", "Saisie manuelle publique"),
                    ("public_erp", "API des établissements publics"),
                    ("sap", "Sortir À Paris"),
                    ("service_public", "Service Public"),
                    ("sirene", "API Sirene INSEE"),
                    ("tourisme-handicap", "Tourisme & Handicap"),
                    ("typeform", "Questionnaires Typeform"),
                    ("typeform_musee", "Questionnaires Typeform Musée"),
                    ("centres-vaccination", "Centres de vaccination"),
                    ("dell", "Dell"),
                    ("outscraper", "Outscraper"),
                    ("scrapfly", "Scrapfly"),
                    ("scrapfly2", "Scrapfly2"),
                    ("tally", "Tally"),
                    ("laposte", "La Poste"),
                ],
                default="public",
                help_text="Nom de la source de données dont est issu cet ERP",
                max_length=100,
                null=True,
                verbose_name="Source",
            ),
        ),
    ]
