# Generated by Django 4.2.15 on 2024-09-19 08:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0169_alter_accessibilite_cheminement_ext_pente_longueur_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3)),
                (
                    "contour",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        help_text="Contour du département",
                        srid=4326,
                        verbose_name="Contour",
                    ),
                ),
            ],
        ),
    ]
