# Generated by Django 4.2.16 on 2024-11-05 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0171_external_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalsource",
            name="erp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sources",
                to="erp.erp",
                verbose_name="Établissement",
            ),
        ),
        migrations.AlterField(
            model_name="externalsource",
            name="source_id",
            field=models.CharField(help_text="Identifiant externe de cet ERP", max_length=255),
        ),
    ]
