# Generated by Django 4.2.16 on 2024-11-07 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0172_external_source_id_length"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="externalsource",
            unique_together={("source", "erp")},
        ),
    ]
