# Generated by Django 4.2.16 on 2024-11-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0173_external_source_unicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalsource",
            name="source_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Identifiant externe de cet ERP",
                max_length=255,
                null=True,
            ),
        ),
    ]
