# Generated by Django 5.2.6 on 2025-09-25 08:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0176_source_panoramax"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_ascenceur_accessibilite",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu ou sans objet")],
                null=True,
                verbose_name="Accessibilité de l’ascenseur",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_ascenceur_etage",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu ou sans objet")],
                null=True,
                verbose_name="Ascenceur desservant les étages",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_classes_accessibilite",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aucune", "Aucune salle de classe"),
                    ("partielle", "Au moins une salle de classe (accessibilité partielle des salles)"),
                    ("toutes", "Toutes les salles de classe (accessibilité totale des salles)"),
                ],
                null=True,
                verbose_name="Accessibilité des salles de classes",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_espaces_ouverts",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("restauration", "A la cantine ou l’espace restauration"),
                        ("bibliotheque", "A la bibliothèque ou CDI"),
                        ("cour", "Dans la cour"),
                        (
                            "sante",
                            "Dans les locaux de santé (infirmerie, bureau du médecin scolaire, bureau du psychologue, etc)",
                        ),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="Accessibilité des différents espaces ouverts aux élèves ou étudiants",
            ),
        ),
    ]
