# Generated by Django 5.2.7 on 2025-10-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0177_school"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accessibilite",
            old_name="accueil_ascenceur_accessibilite",
            new_name="accueil_ascenceur_etage_pmr",
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="accueil_classes_accessibilite",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aucune", "Aucune salle de classe"),
                    ("partielle", "Au moins une salle de classe (accessibilité partielle des salles)"),
                    ("toutes", "Toutes les salles de classe (accessibilité totale des salles)"),
                    (None, "Inconnu"),
                ],
                null=True,
                verbose_name="Accessibilité des salles de classes",
            ),
        ),
    ]
