# Generated by Django 4.2.20 on 2025-10-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0178_accueil_ascenceur_etage_pmr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessibilite",
            name="accueil_ascenceur_etage_pmr",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Accessibilité de l’ascenseur",
            ),
        ),
    ]
