# Generated by Django 4.2.20 on 2025-10-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0179_alter_accessibilite_accueil_ascenceur_etage_pmr"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accessibilite",
            old_name="accueil_ascenceur_etage_pmr",
            new_name="accueil_ascenseur_etage_pmr",
        ),
        migrations.RemoveField(
            model_name="accessibilite",
            name="accueil_ascenceur_etage",
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_ascenseur_etage",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (True, "Oui"),
                    (False, "Non"),
                    (None, "Inconnu ou sans objet"),
                ],
                null=True,
                verbose_name="Ascenseur desservant les étages",
            ),
        ),
    ]
