# Generated by Django 5.2.7 on 2025-10-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0180_rename_accueil_ascenceur_etage_pmr_accessibilite_accueil_ascenseur_etage_pmr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_cheminement_ascenseur_pmr",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Accessibilité de l’ascenseur",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="cheminement_ext_ascenseur_pmr",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Accessibilité de l’ascenseur",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="entree_ascenseur_pmr",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Accessibilité de l’ascenseur",
            ),
        ),
    ]
