# Generated by Django 5.2.8 on 2025-12-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0181_elevator_accessibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_isoloir_accessibilite",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Accessibilité de l'isoloir",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_urne_accessibilite",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Accessibilité de l'urne",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="transport_bureau_de_vote_accessibilite",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Accessibilité du service municipal de transport",
            ),
        ),
    ]
