# Generated by Django 5.2.8 on 2026-01-14 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0182_accessibilite_accueil_isoloir_accessibilite_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS reversion_version_object_id_idx 
            ON reversion_version USING btree(object_id);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS reversion_version_object_id_idx;
            """,
        ),
    ]
