# Generated by Django 6.0.1 on 2026-01-28 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0183_add_reversion_index"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DROP INDEX IF EXISTS reversion_version_object_id_idx;
            """,
            reverse_sql="""
            CREATE INDEX IF NOT EXISTS reversion_version_object_id_idx
            ON reversion_version USING btree(object_id);
            """,
        ),
    ]
