# Generated by Django 6.0.2 on 2026-05-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0184_remove_reversion_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_signaletique_interieure",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu ou sans objet")],
                null=True,
                verbose_name="Signalétique intérieure",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="cheminement_ext_signaletique_exterieure",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu ou sans objet")],
                null=True,
                verbose_name="Signalétique extérieure",
            ),
        ),
    ]
