# Generated by Django 6.0.2 on 2026-04-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0184_remove_reversion_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="erp",
            name="rpa_exemption",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Présence d'une dérogation",
                null=True,
                verbose_name="Présence d'une dérogation",
            ),
        ),
    ]
