# Generated by Django 6.0.2 on 2026-05-16 22:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0185_accessibilite_accueil_signaletique_interieure_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_consultation_domicile",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Consultations à domicile",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_prise_en_charge_patients",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        (
                            "preparation",
                            "Préparation à la consultation ou visite préalable pour les personnes ayant un handicap mental ou psychique",
                        ),
                        (
                            "organisation",
                            "Organisation spécifique pour réduire le temps d’attente pour les personnes ayant un handicap mental ou psychique",
                        ),
                        ("outils_communication", "Outils de communication simplifiés pour expliquer les actes"),
                        ("materiel_auscultation", "Matériel d’auscultation adaptés aux personnes obèses"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                null=True,
                verbose_name="Prise en charge des patients",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_salle_consultation_accessible",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Accessibilité de la salle de consultation",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_soignant",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Soignant sensibilisé ou formé",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_soignant_experience",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("visuel", "Visuel"),
                        ("auditif", "Auditif"),
                        ("moteur", "Moteur"),
                        ("mental_psychique", "Mental ou psychique"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                null=True,
                verbose_name="Expérience du soignant concernant les types de handicap",
            ),
        ),
    ]
