# Generated by Django 6.0.2 on 2026-05-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0186_add_accessibilite_lieux_de_sante"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="accessibilite",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("accueil_soignant", True), ("accueil_soignant__isnull", False)),
                    ("accueil_soignant_experience__isnull", True),
                    ("accueil_soignant_experience", []),
                    _connector="OR",
                ),
                name="erp_accessibilite_accueil_soignant_consistency",
            ),
        ),
    ]
