# Generated by Django 6.0.2 on 2026-05-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0187_add_accessibilite_lieux_de_sante_constraint"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="accessibilite",
            name="erp_accessibilite_cheminement_ext_presence_consistency",
        ),
        migrations.AddConstraint(
            model_name="accessibilite",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("cheminement_ext_presence", True), ("cheminement_ext_presence__isnull", False)),
                    models.Q(
                        ("cheminement_ext_terrain_stable__isnull", True),
                        ("cheminement_ext_plain_pied__isnull", True),
                        ("cheminement_ext_pente_presence__isnull", True),
                        ("cheminement_ext_devers__isnull", True),
                        ("cheminement_ext_bande_guidage__isnull", True),
                        ("cheminement_ext_retrecissement__isnull", True),
                        ("cheminement_ext_signaletique_exterieure__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="erp_accessibilite_cheminement_ext_presence_consistency",
            ),
        ),
    ]
