# Generated by Django 6.0.5 on 2026-05-21 13:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0185_alter_erp_source_alter_externalsource_source"),
        ("erp", "0188_update_cheminement_ext_presence_constraint"),
    ]

    operations = []
