# Generated by Django 6.0.7 on 2026-08-03 20:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0190_rpa"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="accessibilite",
            name="erp_accessibilite_sanitaires_presence_consistency",
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_aire_de_jeux",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Accessibilité de l'aire de jeux à une personne en fauteuil",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_casiers",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Présence de casiers",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_casiers_adaptes",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Casiers adaptés",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_casiers_fermeture",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("serrure_avec_cle", "Serrure avec clé"),
                        ("serrure_electronique_a_code", "Serrure électronique à code"),
                        ("serrure_mecanique_a_code", "Serrure mécanique à code"),
                        ("verrou_cadenas", "Verrou pour cadenas personnel"),
                        ("autre", "Autre"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                null=True,
                verbose_name="Système de fermeture des casiers",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_douches_collectives",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Présence de cabines de douches collectives",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_douches_collectives_adaptees",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Présence de cabines de douches collectives accessibles",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_douches_individuelles",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Présence de cabines douches individuelles",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_douches_individuelles_adaptees",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Présence de cabines de douches individuelles accessibles",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_physique",
            field=models.CharField(
                blank=True,
                choices=[
                    ("inexistant", "Aucun personnel"),
                    ("non_forme", "Personnel non formé"),
                    ("sensibilise_ou_forme", "Personne sensibilisé ou formé"),
                    (None, "Inconnu"),
                ],
                max_length=25,
                null=True,
                verbose_name="Accueil physique",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_presence_espaces_specifiques",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        (
                            "presence_espace_depose_equipements",
                            "Espace de dépose d'équipements (fauteuils, déambulateurs...)",
                        ),
                        (
                            "presence_espace_repos_sensoriel",
                            "Espace de repos sensoriel (hyposensoriel, d'apaisement...)",
                        ),
                        ("presence_espace_chiens_guides", "Espace destiné aux chiens guides et d'assistance"),
                        (
                            "presence_espace_salle_de_change",
                            "Salle de change destinée aux personnes ayant des handicaps multiples ou complexes",
                        ),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                null=True,
                verbose_name="Présence d’espaces spécifiques",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_prestations_complementaires",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("sonorisation_arbitrage", "Sonorisation de l'arbitrage possible"),
                        ("score_visible", "Score visible depuis les places assises"),
                        (
                            "prestation_espace_depose_equipements",
                            "Espace de dépose d'équipements (fauteuils, déambulateurs...)",
                        ),
                        ("reservation_place_facile_d_acces", "Réservation possible de places facile d'accès"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                null=True,
                verbose_name="Prestations complémentaires",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_tribunes",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Accessibilité des places des tribunes",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_tribunes_localisation_places",
            field=models.CharField(
                blank=True,
                choices=[
                    ("niveau_aire_de_jeux", "Places situées au niveau de l'aire de jeux"),
                    ("reparti_differents_niveaux", "Places répartis différents niveaux des tribunes"),
                    (None, "Inconnu"),
                ],
                max_length=100,
                null=True,
                verbose_name="Localisation des places dans les tribunes",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_tribunes_places",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre de places accessibles pour les personnes en fauteuil roulant",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_tribunes_places_avec_accompagnants",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Nombre de places pour les accompagnants dans les tribunes"
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_vestiaires",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Accessibilité des vestiaires",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="accueil_vestiaires_largeur_passage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("entre_90_et_110", "Entre 90 et 110 cm"),
                    ("superieur_a_110", "Supérieure à 110 cm"),
                    (None, "Inconnu"),
                ],
                max_length=40,
                null=True,
                verbose_name="Largeur de passage pour se rendre dans les vestiaires",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="sanitaires_largeur_porte",
            field=models.CharField(
                blank=True,
                choices=[
                    ("entre_80_et_90", "Entre 80 et 90 cm"),
                    ("entre_90_et_110", "Entre 90 et 110 cm"),
                    (None, "Inconnu"),
                ],
                max_length=40,
                null=True,
                verbose_name="Largeur de porte des toilettes",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="sanitaires_sens_transfert",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gauche", "Gauche"),
                    ("droite", "Droite"),
                    ("gauche_et_droite", "Gauche et droite"),
                    (None, "Inconnu"),
                ],
                max_length=40,
                null=True,
                verbose_name="Sens du transfert",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="sanitaires_urinoirs",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Hauteur des urinoirs",
            ),
        ),
        migrations.AddField(
            model_name="accessibilite",
            name="stationnement_zone_depose_pmr",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Oui"), (False, "Non"), (None, "Inconnu")],
                null=True,
                verbose_name="Aire de dépose PMR",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="accueil_prise_en_charge_patients",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("preparation", "Préparation à la consultation ou visite préalable"),
                        ("organisation", "Organisation spécifique pour réduire le temps d’attente"),
                        ("outils_communication", "Outils de communication simplifiés pour expliquer les actes"),
                        ("materiel_auscultation", "Matériel médical adapté aux personnes obèses"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                null=True,
                verbose_name="Prise en charge des patients",
            ),
        ),
        migrations.AlterField(
            model_name="accessibilite",
            name="accueil_soignant_experience",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("visuel", "Visuel"),
                        ("auditif", "Auditif"),
                        ("moteur", "Moteur"),
                        ("mental", "Mental (déficience intellectuelle)"),
                        ("psychique", "Psychique (psychose, trouble bipolaire)"),
                        ("cognitif", "Cognitif (trouble du spectre de l'autisme, TDAH...)"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                null=True,
                verbose_name="Expérience du soignant concernant les types de handicap",
            ),
        ),
        migrations.AlterField(
            model_name="erp",
            name="checked_up_to_date_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Dernière vérification des informations"
            ),
        ),
        migrations.AddConstraint(
            model_name="accessibilite",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("sanitaires_presence", True), ("sanitaires_presence__isnull", False)),
                    models.Q(("sanitaires_adaptes", None), ("sanitaires_urinoirs", None)),
                    _connector="OR",
                ),
                name="erp_accessibilite_sanitaires_presence_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessibilite",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("sanitaires_adaptes", True), ("sanitaires_adaptes__isnull", False)),
                    models.Q(
                        models.Q(
                            ("sanitaires_largeur_porte__isnull", True),
                            ("sanitaires_largeur_porte", ""),
                            _connector="OR",
                        ),
                        models.Q(
                            ("sanitaires_sens_transfert__isnull", True),
                            ("sanitaires_sens_transfert", ""),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="erp_accessibilite_sanitaires_adaptes_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessibilite",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("accueil_casiers", True), ("accueil_casiers__isnull", False)),
                    models.Q(
                        ("accueil_casiers_adaptes", None),
                        models.Q(
                            ("accueil_casiers_fermeture__isnull", True),
                            ("accueil_casiers_fermeture", []),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="erp_accessibilite_accueil_casiers_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessibilite",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("accueil_tribunes_places", 0),
                        ("accueil_tribunes_places__isnull", True),
                        _connector="OR",
                        _negated=True,
                    ),
                    models.Q(
                        models.Q(
                            ("accueil_tribunes_localisation_places__isnull", True),
                            ("accueil_tribunes_localisation_places", ""),
                            _connector="OR",
                        ),
                        ("accueil_tribunes_places_avec_accompagnants__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="erp_accessibilite_accueil_tribunes_places_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessibilite",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("accueil_vestiaires", True), ("accueil_vestiaires__isnull", False)),
                    ("accueil_vestiaires_largeur_passage__isnull", True),
                    ("accueil_vestiaires_largeur_passage", ""),
                    _connector="OR",
                ),
                name="erp_accessibilite_accueil_vestiaires_consistency",
            ),
        ),
    ]
