from dataclasses import dataclass
from typing import Literal, Set, Optional


@dataclass
class EtalabSchema:
    id: Optional[str]
    transport_station_presence: Optional[bool]
    transport_information: Optional[str]
    stationnement_presence: Optional[bool]
    stationnement_pmr: Optional[bool]
    stationnement_ext_presence: Optional[bool]
    stationnement_ext_pmr: Optional[bool]
    cheminement_ext_presence: Optional[bool]
    cheminement_ext_terrain_accidente: Optional[bool]
    cheminement_ext_plain_pied: Optional[bool]
    cheminement_ext_ascenseur: Optional[bool]
    cheminement_ext_nombre_marches: Optional[int]
    cheminement_ext_reperage_marches: Optional[bool]
    cheminement_ext_main_courante: Optional[bool]
    cheminement_ext_rampe: Optional[Literal["aucune", "fixe", "amovible"]]
    cheminement_ext_pente: Optional[Literal["aucune", "légère", "importante"]]
    cheminement_ext_devers: Optional[Literal["aucun", "léger", "important"]]
    cheminement_ext_bande_guidage: Optional[bool]
    cheminement_ext_retrecissement: Optional[bool]
    entree_reperage: Optional[bool]
    entree_vitree: Optional[bool]
    entree_vitree_vitrophanie: Optional[bool]
    entree_plain_pied: Optional[bool]
    entree_ascenseur: Optional[bool]
    entree_marches: Optional[int]
    entree_marches_reperage: Optional[bool]
    entree_marches_main_courante: Optional[bool]
    entree_marches_rampe: Optional[Literal["aucune", "fixe", "amovible"]]
    entree_dispositif_appel: Optional[bool]
    entree_dispositif_appel_type: Optional[
        Set[Literal["bouton", "sonnette", "Optional[int]erphone", "visiophone"]]
    ]
    entree_balise_sonore: Optional[bool]
    entree_aide_humaine: Optional[bool]
    entree_largeur_mini: Optional[int]
    entree_pmr: Optional[bool]
    entree_pmr_informations: Optional[str]
    accueil_visibilite: Optional[bool]
    accueil_personnels: Optional[Literal["formés", "non-formés"]]
    accueil_equipements_malentendants_presence: Optional[bool]
    accueil_equipements_malentendants: Optional[
        Set[Literal["autres", "bim", "lsf", "scd", "lpc"]]
    ]
    accueil_cheminement_plain_pied: Optional[bool]
    accueil_cheminement_ascenseur: Optional[bool]
    accueil_cheminement_nombre_marches: Optional[int]
    accueil_cheminement_reperage_marches: Optional[bool]
    accueil_cheminement_main_courante: Optional[bool]
    accueil_cheminement_rampe: Optional[
        Literal["aucune", "fixe", "amovible", "aide humaine"]
    ]
    accueil_retrecissement: Optional[bool]
    accueil_prestations: Optional[str]
    sanitaires_presence: Optional[bool]
    sanitaires_adaptes: Optional[int]
    labels: Optional[Set[Literal["autre", "dpt", "mobalib", "th"]]]
    labels_familles_handicap: Optional[
        Set[Literal["auditif", "mental", "moteur", "visuel"]]
    ]
    labels_autre: Optional[str]
    commentaire: Optional[str]
    registre_url: Optional[str]
    conformite: Optional[bool]
