DOMAINES_CHOICES = [
    ("Autre", "Autre"),
    ("Antiquaire", "Antiquaire"),
    ("Accessoires", "Accessoires"),
    ("Administration publique", "Administration publique"),
    ("Aéroport", "Aéroport"),
    ("Agence de travail temporaire", "Agence de travail temporaire"),
    ("Agence de voyage", "Agence de voyage"),
    ("Agence immobilière", "Agence immobilière"),
    ("Agence postale ", "Agence postale "),
    ("Aide sociale à l'enfance : action éducative", "Aide sociale à l'enfance : action éducative"),
    ("Aménagement maison : cuisine salle de bain salon", "Aménagement maison : cuisine salle de bain salon"),
    ("Animalerie", "Animalerie"),
    ("Architecte", "Architecte"),
    ("Armurerie coutellerie", "Armurerie coutellerie"),
    ("Art", "Art"),
    ("Assurance", "Assurance"),
    ("Athlétisme", "Athlétisme"),
    ("Audio prothésiste", "Audio prothésiste"),
    ("Auto école", "Auto école"),
    (
        "Autres établissements pour adultes et familles en difficulté",
        "Autres établissements pour adultes et familles en difficulté",
    ),
    ("Avocat", "Avocat"),
    ("Banques, caisses d'épargne", "Banques, caisses d'épargne"),
    ("Bibliothèque médiathèque", "Bibliothèque médiathèque"),
    ("Bijouterie joaillerie", "Bijouterie joaillerie"),
    ("Blanchisserie teinturerie", "Blanchisserie teinturerie"),
    ("Boucherie ", "Boucherie "),
    ("Boulangerie", "Boulangerie"),
    ("Boulodrome", "Boulodrome"),
    ("Bouquins", "Bouquins"),
    ("Bowling", "Bowling"),
    ("Bricolage aménagement", "Bricolage aménagement"),
    ("Bureau de poste", "Bureau de poste"),
    ("Café et thés", "Café et thés"),
    ("Cafétéria", "Cafétéria"),
    ("Camping caravaning", "Camping caravaning"),
    ("Cantine", "Cantine"),
    ("Cardiologie", "Cardiologie"),
    ("Carrosserie", "Carrosserie"),
    ("Caviste", "Caviste"),
    ("Centre commercial", "Centre commercial"),
    ("Centre de loisirs", "Centre de loisirs"),
    ("Centre de vacances", "Centre de vacances"),
    ("Centre équestre", "Centre équestre"),
    ("Centre religieux", "Centre religieux"),
    ("Chapeaux et couvre-chefs", "Chapeaux et couvre-chefs"),
    ("Charcuterie", "Charcuterie"),
    ("Chaussures", "Chaussures"),
    ("Chirurgien dentiste", "Chirurgien dentiste"),
    ("Chocolatier", "Chocolatier"),
    ("Cigarette électronique", "Cigarette électronique"),
    ("Cimetière", "Cimetière"),
    ("Cinéma ", "Cinéma "),
    ("Clinique", "Clinique"),
    ("Coiffure", "Coiffure"),
    ("Collège", "Collège"),
    ("Commerce automobile", "Commerce automobile"),
    ("Comptable expert-comptable", "Comptable expert-comptable"),
    ("Confiserie", "Confiserie"),
    ("Conservatoire", "Conservatoire"),
    ("Contrôle technique auto", "Contrôle technique auto"),
    ("Cordonnerie serrurerie", "Cordonnerie serrurerie"),
    ("Crèmerie Fromagerie", "Crèmerie Fromagerie"),
    ("Cure thermale", "Cure thermale"),
    ("Cycle vente et entretien", "Cycle vente et entretien"),
    ("Cyclisme", "Cyclisme"),
    ("Débit de boisson", "Débit de boisson"),
    ("Décoration Design", "Décoration Design"),
    ("Dermatologie vénéréologie", "Dermatologie vénéréologie"),
    ("Disquaire", "Disquaire"),
    ("Droguerie quincaillerie bricolage", "Droguerie quincaillerie bricolage"),
    ("École de conduite", "École de conduite"),
    ("École élémentaire", "École élémentaire"),
    ("École maternelle", "École maternelle"),
    ("Électroménager et matériel audio-vidéo", "Électroménager et matériel audio-vidéo"),
    ("Empailleur Taxidermiste", "Empailleur Taxidermiste"),
    ("Encadreur enlumineur", "Encadreur enlumineur"),
    ("Épicerie", "Épicerie"),
    ("Équipements du foyer", "Équipements du foyer"),
    ("Ergothérapeute", "Ergothérapeute"),
    ("Établissement de santé ", "Établissement de santé "),
    ("Exploitation agricole", "Exploitation agricole"),
    ("Fleuriste", "Fleuriste"),
    ("Fruits et légumes", "Fruits et légumes"),
    ("Garage", "Garage"),
    ("Gare avec desserte train à grande vitesse (TAGV)", "Gare avec desserte train à grande vitesse (TAGV)"),
    ("Gare routière", "Gare routière"),
    ("Gare sans desserte train à grande vitesse (TAGV)", "Gare sans desserte train à grande vitesse (TAGV)"),
    ("Gastro-entérologie hépatologie", "Gastro-entérologie hépatologie"),
    ("Glacier", "Glacier"),
    ("Gymnase", "Gymnase"),
    ("Gynécologie médicale", "Gynécologie médicale"),
    ("Gynécologie obstétrique", "Gynécologie obstétrique"),
    ("Herboristerie naturopathie", "Herboristerie naturopathie"),
    ("Hôpital", "Hôpital"),
    ("Horlogerie", "Horlogerie"),
    ("Hôtel", "Hôtel"),
    ("Huissier", "Huissier"),
    ("Hypermarché", "Hypermarché"),
    ("Imprimerie photocopie reliure", "Imprimerie photocopie reliure"),
    ("Infirmier", "Infirmier"),
    ("Information Touristique", "Information Touristique"),
    ("Informatique", "Informatique"),
    ("Instruments et matériel de musique", "Instruments et matériel de musique"),
    ("Jardin botanique et/ou zoologique", "Jardin botanique et/ou zoologique"),
    ("Jardinerie", "Jardinerie"),
    ("Jeux jouets", "Jeux jouets"),
    ("Juriste", "Juriste"),
    ("Laverie", "Laverie"),
    ("Librairie ", "Librairie "),
    ("Lieu de culte", "Lieu de culte"),
    ("Linge maison", "Linge maison"),
    ("Literie", "Literie"),
    ("Location articles loisirs et sport", "Location articles loisirs et sport"),
    ("Location véhicules", "Location véhicules"),
    ("Luminaire", "Luminaire"),
    ("Lycée", "Lycée"),
    ("Mairie", "Mairie"),
    ("Maison de santé ou centre de santé", "Maison de santé ou centre de santé"),
    ("Maroquinerie sellerie articles de voyage", "Maroquinerie sellerie articles de voyage"),
    ("Massages", "Massages"),
    ("Masseur kinésithérapeute", "Masseur kinésithérapeute"),
    ("Médecin généraliste", "Médecin généraliste"),
    ("Mercerie", "Mercerie"),
    ("Meubles ameublement", "Meubles ameublement"),
    ("Motocycle vente et entretien", "Motocycle vente et entretien"),
    ("Musée", "Musée"),
    ("Notaire", "Notaire"),
    ("Ophtalmologie", "Ophtalmologie"),
    ("Optique", "Optique"),
    ("Organisation patronale, professionnelle, syndicale", "Organisation patronale, professionnelle, syndicale"),
    ("Orthopédie", "Orthopédie"),
    ("Orthophonie", "Orthophonie"),
    ("Orthoptie", "Orthoptie"),
    ("Oto-rhino-laryngologie", "Oto-rhino-laryngologie"),
    ("Papeterie journaux ", "Papeterie journaux "),
    ("Parc d’attraction et parc à thème", "Parc d’attraction et parc à thème"),
    ("Parfumerie produits de beauté", "Parfumerie produits de beauté"),
    ("Patinoire", "Patinoire"),
    ("Pâtisserie", "Pâtisserie"),
    ("Pédiatrie", "Pédiatrie"),
    ("Pédicure-podologue", "Pédicure-podologue"),
    ("Pension gîte", "Pension gîte"),
    ("Personnes âgées : foyer restaurant", "Personnes âgées : foyer restaurant"),
    ("Personnes âgées : hébergement", "Personnes âgées : hébergement"),
    ("Petite enfance crèche", "Petite enfance crèche"),
    ("Pharmacie", "Pharmacie"),
    ("Photographie", "Photographie"),
    ("Piscine", "Piscine"),
    ("Plateaux et terrains de jeux extérieurs", "Plateaux et terrains de jeux extérieurs"),
    ("Pneumologie", "Pneumologie"),
    ("Poissonnerie", "Poissonnerie"),
    ("Pompes funèbres", "Pompes funèbres"),
    ("Port", "Port"),
    ("Poterie verrerie céramique", "Poterie verrerie céramique"),
    ("Produits surgelés", "Produits surgelés"),
    ("Profession libérale", "Profession libérale"),
    ("Promotion immobilière", "Promotion immobilière"),
    ("Psychiatrie", "Psychiatrie"),
    ("Psychomotricien", "Psychomotricien"),
    ("Radiodiagnostic et imagerie médicale", "Radiodiagnostic et imagerie médicale"),
    ("Relais poste ", "Relais poste "),
    ("Rempailleur chaises fauteuils", "Rempailleur chaises fauteuils"),
    ("Réparation auto et de matériel agricole", "Réparation auto et de matériel agricole"),
    ("Restaurant", "Restaurant"),
    ("Restaurant scolaire", "Restaurant scolaire"),
    ("Restauration rapide", "Restauration rapide"),
    ("Retouche", "Retouche"),
    ("Revêtements murs et sols", "Revêtements murs et sols"),
    ("Roller-Skate-Vélo bicross ou freestyle", "Roller-Skate-Vélo bicross ou freestyle"),
    ("Sage-femme", "Sage-femme"),
    ("Salle de combat", "Salle de combat"),
    ("salle de danse", "salle de danse"),
    ("Salle de jeux", "Salle de jeux"),
    ("Salle de spectacle", "Salle de spectacle"),
    ("Salle multisports", "Salle multisports"),
    ("Salle non spécialisée", "Salle non spécialisée"),
    ("Salle spécialisée", "Salle spécialisée"),
    ("Salles de remise en forme", "Salles de remise en forme"),
    ("Salon de thé", "Salon de thé"),
    ("Service à domicile", "Service à domicile"),
    ("Sex shop", "Sex shop"),
    ("Soins de beauté", "Soins de beauté"),
    ("Spa", "Spa"),
    ("Sports et loisirs", "Sports et loisirs"),
    ("Sports nautiques", "Sports nautiques"),
    ("Stade", "Stade"),
    ("Station lavage auto", "Station lavage auto"),
    ("Station service", "Station service"),
    ("Stomatologie", "Stomatologie"),
    ("Supérette", "Supérette"),
    ("Supermarché", "Supermarché"),
    ("Tabac", "Tabac"),
    ("Tatouage Piercing", "Tatouage Piercing"),
    ("Téléphonie", "Téléphonie"),
    ("Tennis", "Tennis"),
    ("Textile hors habillement", "Textile hors habillement"),
    ("Théâtre", "Théâtre"),
    ("Toiletteur", "Toiletteur"),
    ("Traiteur", "Traiteur"),
    ("Université ou école supérieure", "Université ou école supérieure"),
    ("Vêtements sous-vêtements lingerie", "Vêtements sous-vêtements lingerie"),
    ("Vétérinaire", "Vétérinaire"),
]
