# Generated by Django 3.2.11 on 2022-05-02 13:00

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('nom', models.CharField(help_text='Nom du challenge', max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, help_text="Identifiant d'URL (slug)", max_length=255, populate_from='nom', unique=True)),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de début du challenge')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin du challenge (inclus)')),
                ('nb_erp_total_added', models.BigIntegerField(default=0)),
                ('classement', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'ordering': ('nom',),
            },
        ),
    ]
