# Generated by Django 3.2.11 on 2022-05-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="start_date",
            field=models.DateTimeField(verbose_name="Date de début du challenge"),
        ),
    ]
