# Generated by Django 3.2.11 on 2022-05-02 13:20
from django.db import migrations
from django.db.migrations import RunPython


def create_challenge(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0002_alter_challenge_start_date"),
    ]

    operations = [RunPython(create_challenge)]
