# Generated by Django 3.2.11 on 2022-05-02 13:20
import datetime

from django.contrib.auth import get_user_model
from django.db import migrations
from django.db.migrations import RunPython

from stats.models import Challenge


def create_challenge(apps, schema_editor):
    User = get_user_model()
    start_date = datetime.datetime(2022, 3, 21, 0, 0, 0)
    stop_date = datetime.datetime(2022, 6, 21, 23, 59, 59)
    user, created = User.objects.get_or_create(username="Vanfrackem")

    challenge = Challenge.objects.create(
        created_by=user,
        nom="Challenge DDT",
        start_date=start_date,
        end_date=stop_date,
    )
    challenge.refresh_stats()


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0002_alter_challenge_start_date"),
    ]

    operations = [RunPython(create_challenge)]
