# Generated by Django 3.2.11 on 2022-05-05 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0003_auto_20220502_1520"),
    ]

    operations = [
        migrations.CreateModel(
            name="Referer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.URLField(help_text="Domaine du site réutilisateur")),
            ],
            options={
                "verbose_name": "Site réutilisateur",
                "verbose_name_plural": "Sites réutilisateur",
                "ordering": ("domain",),
            },
        ),
        migrations.CreateModel(
            name="Implementation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("urlpath", models.URLField(help_text="Url complète")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de détection de tracking"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de dernier contact"
                    ),
                ),
                (
                    "referer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="implementations",
                        to="stats.referer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Implémentation du Widget",
                "verbose_name_plural": "Implémentations du Widget",
                "ordering": ("-updated_at", "urlpath"),
            },
        ),
    ]
