# Generated by Django 3.2.11 on 2022-05-12 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0005_auto_20220509_0913"),
    ]

    operations = []
