# Generated by Django 3.2.11 on 2022-05-12 11:31

from django.db import migrations
from django.db.migrations import RunPython


def delete_implementations(apps, schema_editor):
    Implementation = apps.get_model("stats", "implementation")
    Implementation.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0005_auto_20220509_0913"),
    ]

    operations = [RunPython(delete_implementations)]
