# Generated by Django 3.2.11 on 2022-05-12 11:31

from django.db import migrations
from django.db.migrations import RunPython


def dedoublonnage_referer(apps, schema_editor):
    Referer = apps.get_model("stats", "referer")
    referers = Referer.objects.values("domain").distinct()

    for e in referers:
        list_referer = (
            Referer.objects.filter(domain=e["domain"])
            .order_by("date_notification_to_mattermost")[1:]
            .values_list("pk", flat=True)
        )
        Referer.objects.filter(pk__in=list_referer).delete()


def dedoublonnage_implementation(apps, schema_editor):
    Implementation = apps.get_model("stats", "implementation")
    implementations = Implementation.objects.values("urlpath").distinct()

    for e in implementations:
        list_implementation = (
            Implementation.objects.filter(urlpath=e["urlpath"]).order_by("created_at")[1:].values_list("pk", flat=True)
        )
        Implementation.objects.filter(pk__in=list_implementation).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0006_manual_implementation"),
    ]

    operations = [
        RunPython(dedoublonnage_referer),
        RunPython(dedoublonnage_implementation),
    ]
