# Generated by Django 3.2.13 on 2022-05-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0007_auto_20220512_1331"),
    ]

    operations = [
        migrations.AlterField(
            model_name="implementation",
            name="urlpath",
            field=models.URLField(help_text="Url complète", unique=True),
        ),
        migrations.AlterField(
            model_name="referer",
            name="domain",
            field=models.URLField(help_text="Domaine du site réutilisateur", unique=True),
        ),
    ]
