# Generated by Django 3.2.13 on 2022-06-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0008_auto_20220518_2242"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="implementation",
            index=models.Index(fields=["referer"], name="referer_idx"),
        ),
        migrations.AddIndex(
            model_name="implementation",
            index=models.Index(fields=["urlpath"], name="urlpath_idx"),
        ),
        migrations.AddIndex(
            model_name="referer",
            index=models.Index(fields=["domain"], name="domain_idx"),
        ),
    ]
