# Generated by Django 3.2.13 on 2022-06-22 09:27

from django.db import migrations
from django.db.migrations import RunPython

from stats.models import GlobalStats


def create_global_stats(*args, **kwargs):
    GlobalStats.refresh_stats()


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0010_globalstats"),
    ]

    operations = [RunPython(create_global_stats)]
