# Generated by Django 3.2.13 on 2022-06-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_auto_20220622_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='accroche',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='objectif',
            field=models.TextField(blank=True, null=True),
        ),
    ]
