# Generated by Django 3.2.15 on 2022-10-17 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stats", "0012_auto_20220630_1040"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengePlayer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inscription_date",
                    models.DateTimeField(verbose_name="Date d'inscription"),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stats.challenge",
                        verbose_name="Challenge",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Challenge",
                "verbose_name_plural": "Challenges",
                "ordering": ("inscription_date",),
            },
        ),
        migrations.AddField(
            model_name="challenge",
            name="players",
            field=models.ManyToManyField(
                related_name="challenge_players",
                through="stats.ChallengePlayer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
