# Generated by Django 3.2.15 on 2022-10-17 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stats", "0013_auto_20221017_1247"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="challengeplayer",
            options={
                "ordering": ("inscription_date",),
                "verbose_name": "Challenge Player",
                "verbose_name_plural": "Challenges Players",
            },
        ),
        migrations.AlterField(
            model_name="challengeplayer",
            name="inscription_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date d'inscription"
            ),
        ),
        migrations.AlterField(
            model_name="challengeplayer",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Joueur",
            ),
        ),
    ]
