# Generated by Django 3.2.15 on 2022-10-17 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0014_auto_20221017_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeplayer',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='stats.challenge', verbose_name='Challenge'),
        ),
        migrations.AlterField(
            model_name='challengeplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Joueur'),
        ),
    ]
