# Generated by Django 3.2.15 on 2022-11-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0001_squashed_0015_auto_20221017_1549"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="text_reserve",
            field=models.TextField(blank=True, null=True),
        ),
    ]
