# Generated by Django 3.2.15 on 2022-11-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0016_challenge_text_reserve"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="classement",
            field=models.JSONField(default="{}"),
        ),
    ]
