# Generated by Django 3.2.16 on 2022-12-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0017_alter_challenge_classement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="classement",
            field=models.JSONField(default=dict),
        ),
    ]
