# Generated by Django 4.2.1 on 2023-09-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0018_alter_challenge_classement"),
    ]

    operations = [
        migrations.CreateModel(
            name="WidgetEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("domain", models.URLField(help_text="Domaine du site réutilisateur")),
                ("referer_url", models.URLField(help_text="Url complète")),
                ("views", models.IntegerField(default=0)),
            ],
            options={
                "unique_together": {("domain", "referer_url", "date")},
            },
        ),
    ]
