# Generated by Django 4.2.3 on 2023-10-10 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0019_widgetevent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Implementation",
        ),
        migrations.DeleteModel(
            name="Referer",
        ),
    ]
