# Generated by Django 4.2.3 on 2024-02-13 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0020_remove_implem_widget_referer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalstats",
            name="stats_territoires_sort_count",
        ),
        migrations.RemoveField(
            model_name="globalstats",
            name="stats_territoires_sort_default",
        ),
    ]
