# Generated by Django 4.2.11 on 2024-04-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0021_challenge_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="users_can_register",
            field=models.BooleanField(
                default=True,
                help_text="Les utilisateurs peuvent-ils s'inscrire d'eux mêmes au challenge?",
            ),
        ),
    ]
