# Generated by Django 4.2.11 on 2024-07-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0022_challenge_user_can_register"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GlobalStats",
        ),
        migrations.AlterField(
            model_name="challenge",
            name="users_can_register",
            field=models.BooleanField(
                default=True,
                help_text="Les utilisateurs peuvent-ils s'inscrire d'eux mêmes au challenge?",
                verbose_name="Les utilisateur s'auto inscrivent",
            ),
        ),
    ]
