# Generated by Django 5.2.7 on 2025-10-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0023_delete_globalstats_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="objectif",
            field=models.TextField(blank=True, null=True, verbose_name="Règles du jeu"),
        ),
    ]
