# Generated by Django 5.2.7 on 2025-11-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0024_accueil_ascenceur_etage_pmr"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="widgetevent",
            index=models.Index(fields=["date", "domain"], name="idx_widgetevent_date_domain"),
        ),
    ]
