# Generated by Django 6.0.7 on 2026-07-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0025_widget_event_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="accroche",
            field=models.TextField(blank=True, default=str),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="challenge",
            name="objectif",
            field=models.TextField(blank=True, default=str, verbose_name="Règles du jeu"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="challenge",
            name="text_reserve",
            field=models.TextField(blank=True, default=str),
            preserve_default=False,
        ),
    ]
