# Generated by Django 6.0.7 on 2026-10-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0026_alter_challenge_accroche_alter_challenge_objectif_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WidgetDomainMonth",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.URLField(help_text="Domaine du site réutilisateur")),
                (
                    "month",
                    models.DateField(
                        help_text="Premier jour du mois d'observation",
                        verbose_name="Mois",
                    ),
                ),
                ("total_views", models.BigIntegerField(default=0, verbose_name="Vues cumulées")),
            ],
            options={
                "verbose_name": "Domaine du widget (mois)",
                "verbose_name_plural": "Domaines du widget (mois)",
                "ordering": ("-month", "domain"),
            },
        ),
        migrations.AddConstraint(
            model_name="WidgetDomainMonth",
            constraint=models.UniqueConstraint(
                fields=("domain", "month"),
                name="unique_widget_domain_month",
            ),
        ),
    ]
