# Generated by Django 6.0.7 on 2026-10-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0026_alter_challenge_accroche_alter_challenge_objectif_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WidgetDomain",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.URLField(help_text="Domaine du site réutilisateur", unique=True)),
                (
                    "first_seen",
                    models.DateField(
                        help_text="Première date d'observation du domaine",
                        verbose_name="Première observation",
                    ),
                ),
                (
                    "last_seen",
                    models.DateField(
                        help_text="Dernière date d'observation du domaine",
                        verbose_name="Dernière observation",
                    ),
                ),
                ("total_views", models.BigIntegerField(default=0, verbose_name="Vues cumulées")),
            ],
            options={
                "verbose_name": "Domaine du widget",
                "verbose_name_plural": "Domaines du widget",
                "ordering": ("-last_seen", "domain"),
            },
        ),
    ]
