from .access_doors import DOOR_QUESTION, DOOR_SIZE_QUESTION, DOOR_TYPE_QUESTION
from .access_steps import STEP_DIRECTION_QUESTION, STEP_NUMBER_QUESTION, STEP_QUESTION, STEP_RAMP_QUESTION

CONTRIBUTION_QUESTIONS = [
    STEP_QUESTION,
    STEP_NUMBER_QUESTION,
    STEP_DIRECTION_QUESTION,
    STEP_RAMP_QUESTION,
    DOOR_QUESTION,
    DOOR_TYPE_QUESTION,
    DOOR_SIZE_QUESTION,
]
