from .access_steps import STEP_DIRECTION_QUESTION, STEP_NUMBER_QUESTION, STEP_QUESTION, STEP_RAMP_QUESTION

CONTRIBUTION_QUESTIONS = [STEP_QUESTION, STEP_NUMBER_QUESTION, STEP_DIRECTION_QUESTION, STEP_RAMP_QUESTION]
