# Generated by Django 4.2.16 on 2024-12-05 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("contact", "0001_initial"),
        ("contact", "0002_auto_20200908_1551"),
        ("contact", "0003_auto_20200914_1720"),
        ("contact", "0003_auto_20200914_1638"),
        ("contact", "0004_merge_20200916_1733"),
        ("contact", "0005_alter_message_topic"),
        ("contact", "0006_alter_message_email"),
        ("contact", "0007_api_key"),
        ("contact", "0008_remove_vaccination_topic"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("erp", "0001_squashed_0140_auto_20220901_1426"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("a11y", "Problème d'accessibilité"),
                            ("bug", "Rapport de bug"),
                            ("support", "Demande d'aide"),
                            ("contact", "Prise de contact"),
                            ("partenariat", "Proposition de partenariat"),
                            ("signalement", "Signalement d'un problème de données"),
                            ("autre", "Autre demande"),
                        ],
                        default="contact",
                        max_length=50,
                        verbose_name="Sujet",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True, verbose_name="Votre nom")),
                ("email", models.EmailField(max_length=255, verbose_name="Adresse email")),
                ("body", models.TextField(max_length=5000, verbose_name="Message")),
                ("sent_ok", models.BooleanField(default=False, verbose_name="Envoi OK")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Date de création")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Dernière modification")),
                ("erp", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="erp.erp")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [models.Index(fields=["topic"], name="contact_mes_topic_4a6e9c_idx")],
            },
        ),
        migrations.AlterField(
            model_name="message",
            name="topic",
            field=models.CharField(
                choices=[
                    ("bug", "Bug technique"),
                    ("connection", "Problème de connexion"),
                    ("address", "Adresse non reconnue"),
                    ("deletion", "Suppression d'un établissement"),
                    ("contact", "Prise de contact avec Acceslibre"),
                    ("api", "API"),
                    ("signalement", "Signaler une malveillance"),
                    ("vaccination", "Vaccination"),
                    ("autre", "Autre"),
                ],
                default="contact",
                max_length=50,
                verbose_name="Sujet",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="email",
            field=models.EmailField(error_messages={"invalid": ""}, max_length=255, verbose_name="Adresse email"),
        ),
        migrations.AlterField(
            model_name="message",
            name="topic",
            field=models.CharField(
                choices=[
                    ("bug", "Bug technique"),
                    ("connection", "Problème de connexion"),
                    ("address", "Adresse non reconnue"),
                    ("deletion", "Suppression d'un établissement"),
                    ("contact", "Prise de contact avec Acceslibre"),
                    ("api", "API"),
                    ("signalement", "Signaler une malveillance"),
                    ("vaccination", "Vaccination"),
                    ("api_key", "Clef API"),
                    ("autre", "Autre"),
                ],
                default="contact",
                max_length=50,
                verbose_name="Sujet",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="topic",
            field=models.CharField(
                choices=[
                    ("bug", "Bug technique"),
                    ("connection", "Problème de connexion"),
                    ("address", "Adresse non reconnue"),
                    ("deletion", "Suppression d'un établissement"),
                    ("contact", "Prise de contact avec Acceslibre"),
                    ("api", "API"),
                    ("signalement", "Signaler une malveillance"),
                    ("api_key", "Clef API"),
                    ("autre", "Autre"),
                ],
                default="contact",
                max_length=50,
                verbose_name="Sujet",
            ),
        ),
    ]
