# Generated by Django 3.1.1 on 2020-09-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_auto_20200908_1551"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="topic",
            field=models.CharField(
                choices=[
                    ("a11y", "Problème d'accessibilité"),
                    ("bug", "Rapport de bug"),
                    ("support", "Demande d'aide"),
                    ("contact", "Prise de contact"),
                    ("partenariat", "Proposition de partenariat"),
                    ("signalement", "Signalement d'un problème de données"),
                    ("autre", "Autre demande"),
                ],
                default="contact",
                max_length=50,
                verbose_name="Sujet",
            ),
        ),
    ]
