# Generated by Django 3.2 on 2021-05-06 19:30
from django.db import migrations, models

from contact.models import Message as MessageModel


def change_category(apps, schema_editor):
    Message: MessageModel = apps.get_model("contact", "Message")
    messages = Message.objects.all()
    topics = [topic[0] for topic in MessageModel.TOPICS]
    for m in messages:
        if m.topic not in topics:
            m.topic = "autre"
            m.save()


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0004_merge_20200916_1733"),
    ]

    operations = [
        migrations.RunPython(change_category),
        migrations.AlterField(
            model_name="message",
            name="topic",
            field=models.CharField(
                choices=[
                    ("bug", "Bug technique"),
                    ("connection", "Problème de connexion"),
                    ("address", "Adresse non reconnue"),
                    ("deletion", "Suppression d'un établissement"),
                    ("contact", "Prise de contact avec Acceslibre"),
                    ("api", "API"),
                    ("signalement", "Signaler une malveillance"),
                    ("vaccination", "Vaccination"),
                    ("autre", "Autre"),
                ],
                default="contact",
                max_length=50,
                verbose_name="Sujet",
            ),
        ),
    ]
