# Generated by Django 3.2.5 on 2022-03-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0005_alter_message_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="email",
            field=models.EmailField(
                error_messages={"invalid": ""},
                max_length=255,
                verbose_name="Adresse email",
            ),
        ),
    ]
