# Generated by Django 4.2.3 on 2023-12-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0007_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="topic",
            field=models.CharField(
                choices=[
                    ("bug", "Bug technique"),
                    ("connection", "Problème de connexion"),
                    ("address", "Adresse non reconnue"),
                    ("deletion", "Suppression d'un établissement"),
                    ("contact", "Prise de contact avec Acceslibre"),
                    ("api", "API"),
                    ("signalement", "Signaler une malveillance"),
                    ("api_key", "Clef API"),
                    ("autre", "Autre"),
                ],
                default="contact",
                max_length=50,
                verbose_name="Sujet",
            ),
        ),
    ]
