# Generated by Django 4.2.16 on 2024-12-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial_squashed_0008_remove_vaccination_topic"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("general", "Utilisation générale d'acceslibre"),
                            ("contrib", "Contribution"),
                            ("data", "Accès aux données"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "title_fr",
                    models.CharField(max_length=255, null=True, verbose_name="Titre"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=255, null=True, verbose_name="Titre"),
                ),
                ("description", models.TextField()),
                ("description_fr", models.TextField(null=True)),
                ("description_en", models.TextField(null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Dernière modification"),
                ),
            ],
        ),
    ]
