# Generated by Django 5.2.2 on 2025-10-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0009_faq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="section",
            field=models.CharField(
                choices=[
                    ("tutorials", "Tutoriels"),
                    ("general", "Utilisation générale d'acceslibre"),
                    ("contrib", "Contribution"),
                    ("data", "Accès aux données"),
                ],
                default="general",
                max_length=50,
            ),
        ),
    ]
