# Generated by Django 3.2 on 2021-06-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailtoken",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "EmailToken",
                "verbose_name_plural": "EmailTokens",
            },
        ),
        migrations.RemoveIndex(
            model_name="emailtoken",
            name="authenticat_token_345976_idx",
        ),
        migrations.RenameField(
            model_name="emailtoken",
            old_name="token",
            new_name="activation_token",
        ),
        migrations.AddIndex(
            model_name="emailtoken",
            index=models.Index(
                fields=["activation_token"], name="authenticat_activat_a7e735_idx"
            ),
        ),
    ]
