# Generated by Django 3.2.4 on 2021-06-29 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("compte", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
                (
                    "notify_on_unpublished_erps",
                    models.BooleanField(
                        default=True,
                        verbose_name="Accepte les mails de rappel de publication",
                    ),
                ),
            ],
            options={
                "verbose_name": "UserPreferences",
                "verbose_name_plural": "UsersPreferences",
            },
        ),
    ]
