# Generated by Django 4.2 on 2023-05-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compte", "0004_user_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstats",
            name="nb_profanities",
            field=models.IntegerField(default=0),
        ),
    ]
