# Generated by Django 4.2.1 on 2023-10-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compte", "0005_profanity"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="newsletter_opt_in",
            field=models.BooleanField(default=False, verbose_name="J'accepte de recevoir la newsletter"),
        ),
    ]
