# Generated by Django 4.2.3 on 2024-03-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compte", "0006_userpreferences_newsletter_opt_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreferences",
            name="newsletter_opt_in",
            field=models.BooleanField(default=False, verbose_name="Accepte de recevoir la newsletter"),
        ),
    ]
