name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: chartboost/ruff-action@e18ae971ccee1b2d7bbef113930f00c670b78da4
